### ISSUE TITLE
how to display infotext (checkbox explanations) in german?

### ISSUE THREAD

**Issue by berteh** [sdaps/sdaps#102]
Hello.
sdaps looks promissing, thanks. I just cannot manage to get the "technical info" (infotext?) block to print in german instead of english

My umfrage.tex works great with "english" option on the sdaps \documentclass, but if I use "ngerman" instead an error is reported: "you haven't specified a language option". 

Using ``\usepackage[ngerman]{babel}`` leads me to same error "you haven't specified a language option".
Any idea?
thanks !

**Comment by benzea** [comment]
Are you sure that you have the ngerman language pack installed in texlive?

**Comment by berteh** [comment]
indeed a ``sudo apt-get install  texlive-lang-german`` fix it, sorry for bothering. - feeling stupid -
