### ISSUE TITLE
how to not print any barcode?

### ISSUE THREAD

**Issue by berteh** [sdaps/sdaps#103]
I have no (manual) use for any barcode, and would like not to scare my audience with a though that they may be tracked. Is there any way to get completely rid of it in the pdf ?

**Comment by benzea** [comment]
You need the barcode to detect page number and rotation. The only "alternative" is the "classic" style that you can enable which then uses filled dots in the corners (people tend to fill them though making reading impossible).

**Comment by benzea** [comment]
Hmm, one could probably just hide the border of those corner boxes. Then people wouldn't be tempted to fill them in.

**Comment by berteh** [comment]
indeed, classic mode suits this purpose thanks.

If you find some time to hack a version to completely hide the unfilled corner box (or replace with "times" sign or anything else) that'd be lovely, but don't rush it !

**Comment by benzea** [comment]
It is quite simple to change (I just checked that the outline is not used which is the case for checkboxes). All you need to do is change sdaps.cls, look for (there should be a block for each corner):

          \if@style@classic%
            \ifcase\thepage%
              % Case 0
              \draw (\boxpaddings, -\boxpaddings) rectangle +(\cornerboxsize,-\cornerboxsize);%
            \or%
              % Case 1
              \draw (\boxpaddings, -\boxpaddings) rectangle +(\cornerboxsize,-\cornerboxsize);%
            \or%
              % Case 2
              \fill (\boxpaddings, -\boxpaddings) rectangle +(\cornerboxsize,-\cornerboxsize);%

Then simply delete all cases of \draw.
