### ISSUE TITLE
Tutorial example uses now-undefined old font command \tt

### ISSUE THREAD

**Issue by ysalmon** [sdaps/sdaps#104]
When trying to follow the tutorial from the SDAPS website, I fail to setup the project because the compilation of the example .tex file fails under TexLive 2017 with the error
```
Class scrartcl Error: undefined old font command `\tt'.
```
I also get an error about old font command ```\bf``` when trying the example in issue #11

**Comment by benzea** [comment]
Thanks, I updated the example file to again match the example.tex found in the stable release.

Yeah, you need to simply use \textbf in this case too. Note though that I should really redo the example with the new class as it has infrastructure in place which should make it slightly nicer to do such things (it isn't really bad though).
