### ISSUE TITLE
SDAPS should print out name of main output file

### ISSUE THREAD

**Issue by ysalmon** [sdaps/sdaps#105]
I am trying to automate the ideas of #11 and integrate them with my scripts to manage grades.

I generate a questionnaire from a database of students names and [run sdaps on it](https://framagit.org/ysalmon/gestion-notes/blob/03e280c490c837cde5b1637e596dbd4c04d12d9b/qcm.py#L53). It works, but my script does not know the name of the PDF file that was created.

It would be useful if sdaps would print this file name after completion.

**Comment by benzea** [comment]
You can specify the output filename. Would that work for you?

I am fine with adding it to the output (and I think that actually makes sense), but such an output would likely be designed to be human readable rather than scriptable.

**Comment by ysalmon** [comment]
Of course it would ; I did not even think about checking I could. I am stupid, sorry for the disturbance.

For reference : ``sdaps PROJECT stamp -o OUTFILENAME``

**Comment by benzea** [comment]
Don't worry, easy to miss :)
