### ISSUE TITLE
Bracketed questionnaire_id in CSV

### ISSUE THREAD

**Issue by ysalmon** [sdaps/sdaps#107]
In 1.2.0, the generated CSV file presents the questionnaire_id in this way : ```['71']```. In my ids file, the corresponding id is ```71```, without brackets or quotes.
Is this behaviour normal and stable ? I would have understood the quotes as string delimiter as ids may be non-numeric, but why the brackets ?

**Comment by benzea** [comment]
Hmm, probably the list for each page. Not sure why though right now.

**Comment by benzea** [comment]
Fixed, forgot to cherry-pick 6de5526aa926a9808a956adf4cd376730d7d41ef to stable.
