### ISSUE TITLE
report_tex throws KeyError:1

### ISSUE THREAD

**Issue by egga72** [sdaps/sdaps#108]
Hello togehter,

I intend to use SDAPS for the survays of my master thesis. Everything is working fine so far except the TEX report feature. If i run the report_tex command without added filled questionnaires it works and creates a report. When I add filled questionnaires I receive following error message: (using the example questionnaire)

![image](https://user-images.githubusercontent.com/31177931/29493280-6b6a1eb4-8593-11e7-8097-b83fbe84468a.png)

Thanks for your help!

**Comment by benzea** [comment]
Please post the left over files. See the message "An [error] occured during creation of the report. Temporary files left in '/tmp/XXX'.", go into the directory and have a look at the .log file which should tell you what went wrong.

**Comment by egga72** [comment]
Thanks for your quick response.
Unfortunately, there is no .log file in the path. There are only these files:
![image](https://user-images.githubusercontent.com/31177931/29495394-ae21a846-85be-11e7-8aec-451333661c4a.png)

This is the only content of the report.tex file:
```
\documentclass[ngerman,a4paper]{sdapsreport}

    \usepackage{ifxetex}
    \ifxetex
    \else
      \usepackage[utf8]{inputenc}
    \fi
    \usepackage[ngerman]{babel}

    \title{The Title}
    \subject{The Title}
    \author{The Author}

    \addextrainfo{Abgegebene Fragebögen}{4}
    \addextrainfo{Date}{10.03.2013}

    \begin{document}

    \maketitle

    \section*{1 Range Questions}
\begin{choicequestion}{1.1 How often do you use SDAPS?}
```

**Comment by benzea** [comment]
Btw. it is better for me if you paste the command line output in code blocks rather than screenshots. Then I might have also actually read the backtrace form the first post …

Which version are you using right now?

**Comment by egga72** [comment]
I am using the Windows Subsystem for Linux (Bash on Ubuntu for Windows). So I unfortunately can't copy directly from the terminal. I installed SDAPS using the commands: 
```
# add-apt-repository ppa:benjamin-sipsolutions/sdaps
# apt-get update
# apt-get install sdaps
```
The example.tex is from version 1.9.0.

**Comment by benzea** [comment]
Ahh, that makes sense then. The report probably can't yet handle the naming of boxes.

**Comment by benzea** [comment]
Can you share the example scan of the document? I maybe able to use it for (regression) testing then.

Don't have a printer/scanner easily available currently.

**Comment by egga72** [comment]
Please find the files attached. Thank you for your work and the support.


[test.zip](https://github.com/sdaps/sdaps/files/1237175/test.zip)

**Comment by benzea** [comment]
Is this urgent for you? I had to fix quite a lot of stuff and there are still some open issues to look into. So while I'll probably push out fixes to git in a bit, I may not do a release for another week or so.

**Comment by egga72** [comment]
No, this is not so urgent. I only tried to test all components before I put the questionnaire into the format. Would be great if you could fix it :)

**Comment by benzea** [comment]
So, pushed a slew of fixes. There should be no problem if you update to the new version once it is released. However, there are some fixes to the LaTeX class. This means two things:

 * If you update the survey ID may change (you cannot use old printouts anymore)
 * You should not use questionnaire IDs currently (or if you do only ever stamp *one* ID at a time!)

Best thing is to use git master, obviously ;)

**Comment by benzea** [comment]
I pushed out 1.9.1 to everywhere. So this should be fixed if you run an `apt-get update && apt-get upgrade`.

**Comment by egga72** [comment]
Works perfectly. Highly appreciate your help! 
Thank you very much :)
