### ISSUE TITLE
Can't seem to run tutorial

### ISSUE THREAD

**Issue by SergioReis97** [sdaps/sdaps#110]
Linux mint 18.2, 
```
$ python --version
Python 2.7.12
```

Ran this to install,

```
sudo apt-get install texlive-full
sudo apt-get install texmaker
sudo add-apt-repository ppa:benjamin-sipsolutions/sdaps
sudo apt-get update
apt-get install sdaps
```

And then, downloaded example.tex from http://sdaps.org/Documentation/Tutorial/example.tex,
using it like this

` $ sudo sdaps exampleProject setup_tex example.tex` 
And [this](https://pastebin.com/AAppYxsd) was the output.

A folder with the project name is indeed created and contains the following
```
$ ls
code128.tex        sdapsbase.sty     sdapspdf.sty                                translator-sdaps-dictionary-English.dict  translator-sdaps-dictionary-Portuguese.dict
questionnaire.log  sdapsclassic.cls  sdapsreport.cls                             translator-sdaps-dictionary-Finnish.dict  translator-sdaps-dictionary-Spanish.dict
questionnaire.tex  sdapslayout.sty   translator-sdaps-dictionary-Brazilian.dict  translator-sdaps-dictionary-French.dict   translator-sdaps-dictionary-Swedish.dict
sdapsarray.sty     sdaps.opt         translator-sdaps-dictionary-Dutch.dict      translator-sdaps-dictionary-German.dict
```
[This](https://pastebin.com/3nEFsD4N) is the questionnaire.log

Can't seem to find what is wrong. Thanks in advance for any help.

**Comment by benzea** [comment]
Oh, need to update the website. The tutorial is outdated and will *not* run with the unstable release series. The required changes are small, but I don't think I have an example scan at this point.

Changes required are:

 * change the document class to "sdapsclassic" from "sdaps"
 * change the optional parameter to \begin{choicequestion} from [X] where X is the number of columns to [cols=X]

But, as I said, you will need to create your own scan.

**Comment by SergioReis97** [comment]
Fixes it, thanks for the support,
here is the same file with those little changes 
[example.tex](https://pastebin.com/HnxZXSSN)
