### ISSUE TITLE
Wrong Standard_Deviation Calculation

### ISSUE THREAD

**Issue by egga72** [sdaps/sdaps#111]
Hi all,

The calculation of the Standard_Deviation which is shown in the Report_tex and in the Report function does not work propperly.

e.g. 
![2017-10-08_22-18-50](https://user-images.githubusercontent.com/31177931/31320562-d08352c0-ac76-11e7-9253-83fcd2b42585.jpg)

The average value is calculated correctly. But the standard deviation should be 2.185. I think that this can only be a small failure in the calculate.py file but as I am not familiar with Python it would be great if someone could have a look on this.

Thank you in Advance!
Best regards 
Robert

**Comment by benzea** [comment]
Could you test whether the above patch fixes the issue?

**Comment by egga72** [comment]
Hi,

First of all: many thanks for your help! I have adjusted the calculate.py file in the directory "\usr\lib\python2.7\dist-packages\sdaps" accordingly and ran the report_tex function again. Unfortinatly the result stays the same.

Have i done something wrong?

Thank you!

**Comment by benzea** [comment]
Hah, right. Can you also move the "self.mean = self.mean / float(self.range_count)" line up right underneat the first loop? Otherwise self.mean will obviously still not be correct for the standard deviation calculation …

**Comment by egga72** [comment]
I have tried this:

```
if self.count:
            for key in self.range_values:
                self.range_count += self.values[key]

                self.range_values[key] = self.values[key]
                del self.values[key]

            for key in self.values:
                self.values[key] = self.values[key] / float(self.count)

            if self.range_count > 0:
                for key in self.range_values:
                    self.mean += key * self.range_values[key]
					self.mean = self.mean / float(self.range_count)

                for key in self.range_values:
                    self.standard_deviation += self.range_values[key] * pow(key - self.mean, 2)
					
                    # Also devide by count
                    self.range_values[key] = self.range_values[key] / float(self.count)

                self.standard_deviation = math.sqrt(self.standard_deviation / float(self.range_count))

                if hasattr(self, 'ref_count'):
                    self.significant = abs(self.mean - self.ref_mean) > 0.1
```
Still the same result. Could it be possible that the changed code is not executed?

**Comment by benzea** [comment]
Sounds like it. I mean even the first change should change the result in some way.

Though what you did there is wrong in python, as the indentation matters. So it should be:
```
                for key in self.range_values:
                    self.mean += key * self.range_values[key]
                self.mean = self.mean / float(self.range_count)
```

and indented entirely with spaces. How did you install it and how are you running it?

**Comment by benzea** [comment]
A possible check is to just enter something invalid and (e.g. just add random letters outside of a comment) and see if you get a parser error on startup. Then you know the modified file is being read ;-)

**Comment by benzea** [comment]
One more note, SDAPS creates a new report file by default (numbering them) each time. Are you sure you are looking at the latest one?

**Comment by egga72** [comment]
Now I was able to run the changed code (file attached). I've removed sdaps completely and installed it manualy using the setup.py file.
[calculate.zip](https://github.com/sdaps/sdaps/files/1380779/calculate.zip)

The result looks now like this:
![image](https://user-images.githubusercontent.com/31177931/31520647-d901b9d6-afa6-11e7-8258-c4d59cd05641.png)

**Comment by benzea** [comment]
OK, sorry about this, but I won't manage to lock at it again this month
:-/

**Comment by benzea** [comment]
Ah, you forgot to move the

    self.mean = self.mean / float(self.range_count)

line up. As such the standard deviation is being calculated using a mean of 88 instead of 8 in your case.

**Comment by benzea** [comment]
i.e. like this, simply moving the self.mean line further up:

[calculate.py.txt](https://github.com/sdaps/sdaps/files/1434225/calculate.py.txt)

Still needs a few comments as to what is going on there though.

**Comment by benzea** [comment]
Right, my previous commit to fix the issue was utterly broken; that would explain the error in your file.

**Comment by egga72** [comment]
Thank you very much for fixing the calculation - now the results seem to be right.

![2017-11-03_15-42-48](https://user-images.githubusercontent.com/31177931/32379461-e5767784-c0ad-11e7-9e9f-2a9cd63efa50.jpg)

But since I changed the calculation file the scaling of the graph is wrong. Any idea how to fix this?

One additional question: Is it possible to exclude questions from the report?

Thanks, Robert.

**Comment by benzea** [comment]
Hmm, that scaling issue seems like the division was lost. i.e. the line:

https://github.com/sdaps/sdaps/commit/0f005c7b4415672ea46487abf40a59675cebfdba#diff-132645affa3f4e976c4b2243cc569657R197

or this loop with my latest patch:
                for key in self.range_values:
                    self.range_values[key] = self.range_values[key] / float(self.count)

**Comment by benzea** [comment]
OK, pushed. I assume that the fix is correct. Please reopen this ticket or create a new one if you still see issues.
