### ISSUE TITLE
using sdaps as an external module from java application

### ISSUE THREAD

**Issue by dikey94** [sdaps/sdaps#113]
Hi guys,
I have a little project in my head and I'd like to use sdaps together with java application. I'm going to use sdaps for creating pdfs + scanning filled forms.
Do you have any experience in similar matters?
Thanks!

**Comment by SergioReis97** [comment]
SDAPS works great with what ever you want to use since you can easly run it with a couple of commands, I guess you can make a simple class with some commands using ProcessBuilder . The rest is scanning uploading and handling the exported csv.

**Comment by benzea** [comment]
Someone wrote a PHP wrapper at some point. In general, it should be easy, but you are obviously limited to the features available through the command line interface.
  https://github.com/jansenfelipe/sdaps-php

Should one be able to use python then one could make use of more internal API possibilities.

Closing as I see no need for this issue at this point. Feel free to discuss further here (or even better move any discussion to the mailing list).
