### ISSUE TITLE
Not recognizing the bar code of scans due to unclearness?

### ISSUE THREAD

**Issue by roshbosh** [sdaps/sdaps#114]
Due to some poor quality printing, the bar code has become a bit unclear of the questionnaires and this has resulted is the following warning -

Got a wrong survey ID (1.tif, 34)! It is None but it should be 699139032.

I supposed this is due to the bar code being a bit unclear.

The paper is also rotated a bit (boundaries intact), but this is not an issue, as per the documentation.

Anyway around this issue?
Thank you for any help in advance.

**Comment by benzea** [comment]
There is not really a quick workaround AFAIR. There are nasty hacks one can do to simply assume a certain barcode value, but that has the potential of ugly issues too.

Two things would make this more manageable though:
 * We could add a barcode on both sides of the page by default
 * Setting the correct value in the GUI should run the recognition
 * Use QR code by default as it has error correction (this is the case in the new class)

Right now, can you try running the GUI and setting the corresponding flags manually? I *think* (I have not tried for too long) that you should be able to choose the page at the top, set the verified bit and then manually fill in the data. The overlay will likely not be aligned correctly, but it should work.

**Comment by roshbosh** [comment]
Thank you very much for your response.
According to your advise, I attempted to apply a hack where I tried to equate the bar code value of the survey to "None" (as the program is unable to detect a bar code in the scans) using the files in the model folder, however I was unable to proceed successfully. 
I would be really grateful if you can advise me further on how to achieve this. 

If its helpful, I have attached a sample file with the error message I received at the recognition stage.

This is a scan file of two forms (4 pages)- The for the first form, I receive the following warning message, which does not result in any detection.

Warning: Neither 1.tif, 0 or 1.tif, 1 has a known rotation!                     
Warning: Neither 1.tif, 0 or 1.tif, 1 has a known page number!
Warning: No page number for page 1.tif, 0 exists.
Warning: No page number for page 1.tif, 1 exists.
Warning: Got a wrong survey ID (1.tif, 0)! It is None, but should be 699139032.

For the second form, the detection occurs accurately.  The problem is, I have a lot of forms which result in the above warning message and no detection.

Would greatly appreciate in assistance in this regard.

Thank you 

[Sample files.zip](https://github.com/sdaps/sdaps/files/1485575/Sample.files.zip)

**Comment by benzea** [comment]
Try this:
https://gist.github.com/benzea/c43a82382a93c51c44ffabd3306c0e5f

NOTE: You need to make sure that no page is upside down and that the first page is always at the front.

**Comment by roshbosh** [comment]
Thank you so much for the assistance.
This sorted our issue.

Thanks again.
