### ISSUE TITLE
OSX/MacPorts support [help needed]

### ISSUE THREAD

**Issue by benzea** [sdaps/sdaps#12]
It should be possible to get SDAPS running on MacPorts. However, there appear to be some issues currently, which break loading of the image.so library.

If someone wants to look into it. The relevant part should be in image/**init**.py and paths.py line 62. If the path that is constructed there is wrong, then python will not find image.so.
Note that both cases, running standalone from a git checkout, and installing SDAPS should work fine.

**Comment by cyriltw** [comment]
Just wanted to know the current situation of SDAPS on Mac.

**Comment by benzea** [comment]
Last thing I have heard the situation is not great. At least one person was looking into using vagrant rather than running SDAPS natively, because some of the dependencies were hard or impossible to install.

Unfortunately, I cannot give more information at this point.
