### ISSUE TITLE
GUI jumps madly

### ISSUE THREAD

**Issue by Natureshadow** [sdaps/sdaps#124]
Using sdaps gui under KDE 5, and using the laptop touchpad, I have the two columns of the window changing their widths everytime the pointer moves between the widgets. It gets 50% width when entering the right column, moving all the checkboxes to the left, and gets less wide when exiting the widget.

Plugging in a USB mouse and using it "fixes" the issue.

**Comment by benzea** [comment]
Well, this will need some more information or bug triaging. Though I have not actively tried to reproduce it to be honest.

**Comment by benzea** [comment]
Puh, this is so old ... sorry, I'll assume it was a GTK bug and it has been resolved since.
