### ISSUE TITLE
Print number below QR code

### ISSUE THREAD

**Issue by IoAg** [sdaps/sdaps#125]
Hello,

I planning a survey and I am stamping the created PDfs with specific IDs which should also be visible as numbers below the QR code.

Is that possible in sdaps-1.9.1?

Thanks in advance,
Ioannis

**Comment by IoAg** [comment]
Hello Benjamin,

Thank you for your reply. I agree that it is usually not needed to print numbers. In my case it is useful because during the survey we will note down the approximate location of the questionnaire.

For future reference I write my solution below:

In order to add the id as text below the QR code I added the following lines in tex/class/sdapsbase.dtx

`
\cs_new_protected_nopar:Nn \qrcode_render:nn {
 \begin{tabular}{c}
 \qrcode[#1] {#2} \\
 {#2} \\
 \end{tabular}
}
`

**Comment by benzea** [comment]
Just be careful that there is enough distance from the corner marks. Otherwise you will get into trouble after scanning!

I am open to adding an option to the class to change whether the text is displayed! Note that you could also access it in any other location by inserting \qid (just be careful that it will not cause other things to move around, e.g. use "\strut\qid" to define the height and make sure the line is long enough).

**Comment by IoAg** [comment]
Thanks for the warnings! 

I have printed some sample questionnaires and they seem to be recognized correctly. Are the distances shown below enough?

![screenshot from 2018-02-07 16-15-04](https://user-images.githubusercontent.com/28091775/35924150-844ae01a-0c22-11e8-8d66-5bc0e22f0389.png)

**Comment by benzea** [comment]
I think that should be good!

**Comment by omidraha** [comment]
The same need, I should also show a visible fingerprint below the QR code.

@IoAg Can you please share your code?

**Comment by omidraha** [comment]
@IoAg, Thanks,

After installing `sdaps`, how do you apply this patch?

I just found these related files and not `sdapsbase.dtx`:
```
root@28a9624f4513:/workdir# locate sdapsbase
/usr/share/sdaps/tex/sdapsbase.sty
/ws/omr/backup/sdaps/sdapsbase.sty
/ws/omr/sdaps-31/sdapsbase.sty
/ws/omr/sdaps/sdapsbase.sty
```

**Comment by IoAg** [comment]
In my case I was using sdaps without installation. In the download directory it should be under the path that I wrote before (at least for version 1.9.1). 

I guess you could change the file before installation.
