### ISSUE TITLE
Custom LaTeX layout with sdaps

### ISSUE THREAD

**Issue by nossheart** [sdaps/sdaps#126]
Is there any example of implementing a custom layout with sdaps?

**Comment by nossheart** [comment]
Итак, я нашел FAQ на sdaps.org, но там   нерабочая ссылка на файл-пример custom.tex

**Comment by nossheart** [comment]
Oh, you can just download it at [here](https://sdaps.org/FAQ/custom.tex). Someone needs to fix the link.

**Comment by benzea** [comment]
Sorry about that, fixed the link. It was caused by a stray newline in the source document …
