### ISSUE TITLE
LaTeX Error: File `sdaps.cls' not found.

### ISSUE THREAD

**Issue by dikey94** [sdaps/sdaps#127]
Hello everyone,
I'm just starting my adventure with SDAPS. I've installed the software on Ubuntu 16.04;

`sdaps ./example3 setup_tex example.tex`
gives me

> ------------------------------------------------------------------------------
> - SDAPS -- setup_tex
> ------------------------------------------------------------------------------
> Running pdflatex now twice to generate the questionnaire.
> This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
>  restricted \write18 enabled.
> entering extended mode
> This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
>  restricted \write18 enabled.
> entering extended mode
> This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
>  restricted \write18 enabled.
> entering extended mode
> This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
>  restricted \write18 enabled.
> entering extended mode
> Error running "pdflatex" to compile the LaTeX file.
> Error: An error occured in the setup routine. The survey directory still exists. You can for example check the questionnaire.log file for LaTeX compile errors.
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/sdaps/__init__.py", line 65, in main
>     return cmdline['_func'](cmdline)
>   File "/usr/lib/python2.7/dist-packages/sdaps/cmdline/setuptex.py", line 47, in setup_tex
>     return setuptex.setup(survey, cmdline['questionnaire.tex'], cmdline['additional_questions'], cmdline['add'])
>   File "/usr/lib/python2.7/dist-packages/sdaps/setuptex/__init__.py", line 107, in setup
>     raise AssertionError('PDF file not generated')
> AssertionError: PDF file not generated

I've this in logs:

> This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex 2018.3.17)  17 MAR 2018 17:23
> entering extended mode
>  restricted \write18 enabled.
>  %&-line parsing enabled.
> **questionnaire.tex
> (./questionnaire.tex
> LaTeX2e <2016/02/01>
> Babel <3.9q> and hyphenation patterns for 5 language(s) loaded.
> 
> ! LaTeX Error: File `sdaps.cls' not found.
> 
> Type X to quit or <RETURN> to proceed,
> or enter new name. (Default extension: cls)
> 
> Enter file name: 
> ! Emergency stop.
> <read *> 
>          
> l.29 \usepackage
>                 [utf8]{inputenc}^^M 
> Here is how much of TeX's memory you used:
>  10 strings out of 494910
>  207 string characters out of 6179836
>  45398 words of memory out of 5000000
>  3400 multiletter control sequences out of 15000+600000
>  3640 words of font info for 14 fonts, out of 8000000 for 9000
>  36 hyphenation exceptions out of 8191
>  10i,0n,7p,97b,8s stack positions out of 5000i,500n,10000p,200000b,80000s
> 
> !  ==> Fatal error occurred, no output PDF file produced!
> 

What could be wrong? Thanks!

**Comment by benzea** [comment]
That is odd.

 * How did you install SDAPS?
 * Could you check what files are in the project directory?

As an explanation, the files in `/usr/share/sdaps/tex/` should be automatically copied into the project directory. And then pdflatex should find them just fine.

You could also run `dpkg -L` to check which files the package installed.

**Comment by dikey94** [comment]
I've decided to use Docker image with Ubuntu 16.04. Here all all command I use to install SDAPS:

> RUN apt-get update
> RUN apt-get install -y software-properties-common
> RUN add-apt-repository ppa:benjamin-sipsolutions/sdaps
> RUN apt-get -y update && apt-get -y install sdaps

Full list of project directory:

> -rw-r--r-- 1 root root 17770 Mar 17 18:23 code128.tex
> -rw-r--r-- 1 root root  1007 Mar 17 18:23 questionnaire.log
> -rw-r--r-- 1 root root  5884 Mar 17 18:23 questionnaire.tex
> -rw-r--r-- 1 root root 34149 Mar 17 18:23 sdapsarray.sty
> -rw-r--r-- 1 root root 48954 Mar 17 18:23 sdapsbase.sty
> -rw-r--r-- 1 root root 27454 Mar 17 18:23 sdapsclassic.cls
> -rw-r--r-- 1 root root 18172 Mar 17 18:23 sdapslayout.sty
> -rw-r--r-- 1 root root   727 Mar 17 18:23 sdaps.opt
> -rw-r--r-- 1 root root  3008 Mar 17 18:23 sdapspdf.sty
> -rw-r--r-- 1 root root 10028 Mar 17 18:23 sdapsreport.cls
> -rw-r--r-- 1 root root  1407 Mar 17 18:23 translator-sdaps-dictionary-Brazilian.dict
> -rw-r--r-- 1 root root  1372 Mar 17 18:23 translator-sdaps-dictionary-Dutch.dict
> -rw-r--r-- 1 root root  1340 Mar 17 18:23 translator-sdaps-dictionary-English.dict
> -rw-r--r-- 1 root root  1474 Mar 17 18:23 translator-sdaps-dictionary-Finnish.dict
> -rw-r--r-- 1 root root  1389 Mar 17 18:23 translator-sdaps-dictionary-French.dict
> -rw-r--r-- 1 root root  1369 Mar 17 18:23 translator-sdaps-dictionary-German.dict
> -rw-r--r-- 1 root root  1408 Mar 17 18:23 translator-sdaps-dictionary-Portuguese.dict
> -rw-r--r-- 1 root root  1425 Mar 17 18:23 translator-sdaps-dictionary-Spanish.dict
> -rw-r--r-- 1 root root  1340 Mar 17 18:23 translator-sdaps-dictionary-Swedish.dict

I've listed all files from `/usr/share/sdaps/tex/`. There is no file called `sdaps.cls`

**Comment by benzea** [comment]
Ahh, that entirely explains. You will either need to use a stable release or update your LaTeX file.

You are on the development branch, i.e. version 1.9.x. A lot of new cool features, but also in flux. So be careful to *not* upgrade until you have completely finished your surveys. Other than that, it should work perfectly fine and probably has less issues than the stable branch.
(I am planning to do a 2.0 alpha release soon, which will break *everything* in the sense that you need to start all surveys from scratch.).

Anyway. As you are on 1.9.x you need to port the LaTeX document to the new class. This should be very simple, i.e. change the document class from `sdaps` to `sdapsclassic`. If you used the optional argument for `choicequestion` to set the number of columns, you also need to modify that to say `[cols=X]` rather than just `[X]`. After that you should be good to go.

More documentation: https://sdaps.org/class-doc/ and https://sdaps.org/class-doc/sdapsclassic.html
