### ISSUE TITLE
A unique sheet for each student

### ISSUE THREAD

**Issue by dikey94** [sdaps/sdaps#128]
Hello again,
this time I'm going to create a unique questionnaire for each student (the plan is to use SDAPS for scanning students surveys). 
I've seen #11 and I have 2 questions (there is a gap in my understanding):
1) How can I provide student ids using sdaps commands? I believe it has to be a separated file
2) Can I print student name on each questionnaire?

Thank you.

edit:
1)
```
sdaps ./t23 setup_tex example.tex 
sdaps ./t23 stamp -r 15
```
gives me single questionnaire.pdf, where the text under barcode is NONE

**Comment by benzea** [comment]
Which version are you using now?

You should have a stamp_1.pdf after running that command. The questionnaire.pdf should have a large "draft" text overlay.

**Comment by dikey94** [comment]
It's current stable version (installed 2 days ago).

I've missed stamped_1.pdf, sorry.

This time I'm trying to stamp questionnaires using own ids.
`sdaps ./d2 stamp -f ids`
produces error:
```
------------------------------------------------------------------------------
- SDAPS -- stamp
------------------------------------------------------------------------------
Running pdflatex now twice to generate the stamped questionnaire.
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
Error: Error running "pdflatex" to compile the LaTeX file.
Error: An error occured during creation of the report. Temporary files left in '/tmp/tmpTDgWGJ'.
Traceback (most recent call last):
  File "/usr/bin/sdaps", line 23, in <module>
    sys.exit(sdaps.main())
  File "/usr/lib/python2.7/dist-packages/sdaps/__init__.py", line 64, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/script.py", line 105, in decorated_function
    result = function(cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/cmdline/stamp.py", line 56, in stamp
    return stamp.stamp(survey, output, cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/stamp/__init__.py", line 90, in stamp
    create_stamp_pdf(survey, output_filename, questionnaire_ids)
  File "/usr/lib/python2.7/dist-packages/sdaps/stamp/latex.py", line 48, in create_stamp_pdf
    raise AssertionError('PDF file not generated')
AssertionError: PDF file not generated
```

[questionnaire.log](https://github.com/sdaps/sdaps/files/1834991/questionnaire.log)

Thank you for your time.

**Comment by benzea** [comment]
Is that the questionnaire.log file in from `/tmp/tmpTDgWGJ`?

**Comment by dikey94** [comment]
Nope.
It's ./d2/questionnaire.log

**Comment by dikey94** [comment]
I've moved ./ids into ./ids.txt and... works.
