### ISSUE TITLE
checkmode = set [noinput] option to make it work

### ISSUE THREAD

**Issue by pantzO** [sdaps/sdaps#132]
I would like to use 
checkmode=check 
option.
In the example of the tutorial, when I uncomment the checkmode option and set it to check like this:

% With SDAPS 1.1.6 and newer you can choose the mode used when recognizing
  % checkboxes. valid modes are "checkcorrect" (default), "check" and
  % "fill".
  checkmode=check,

When I try to do
$ sdaps test setup_tex example.tex

I get
------------------------------------------------------------------------------
- SDAPS -- setup_tex
------------------------------------------------------------------------------
Running pdflatex now twice to generate the questionnaire.
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
Error running "pdflatex" to compile the LaTeX file.
Erreur : An error occured in the setup routine. The survey directory still exists. You can for example check the questionnaire.log file for LaTeX compile errors.
Traceback (most recent call last):
  File "/usr/local/bin/sdaps", line 23, in <module>
    sys.exit(sdaps.main())
  File "/usr/local/lib/python2.7/dist-packages/sdaps/__init__.py", line 64, in main
    return cmdline['_func'](cmdline)
  File "/usr/local/lib/python2.7/dist-packages/sdaps/cmdline/setuptex.py", line 47, in setup_tex
    return setuptex.setup(survey, cmdline['questionnaire.tex'], cmdline['additional_questions'], cmdline['add'])
  File "/usr/local/lib/python2.7/dist-packages/sdaps/setuptex/__init__.py", line 120, in setup
    raise AssertionError('PDF file not generated')
AssertionError: PDF file not generated

I'm using sdaps-1.2.1 under Debian 9.

**Comment by benzea** [comment]
Did you have a look at the questionnaire.log file? Maybe that contains more information.

Could be that there is an issue, 1.2.1 is rather old (at least from my view), so not sure right now.

**Comment by pantzO** [comment]
I checked the log file, but there is nothing here...

I got this:

! Package sdaps Error: Sorry, there is no help text for the checkmode you have
choosen right now! Please pass the noinfo optional argument to the questionnair
e environment!.

See the sdaps package documentation for explanation.

1.2.1 is the last stable released (this why I download it).
I'm gonna try with the unstable one.

**Comment by pantzO** [comment]
Same type of error with the last version fetch via github.

$ sdaps test setup_tex example.tex 
------------------------------------------------------------------------------
- SDAPS -- setup
------------------------------------------------------------------------------
Running pdflatex now twice to generate the questionnaire.
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
Error running "pdflatex" to compile the LaTeX file.
Error: An error occured in the setup routine. The survey directory still exists. You can for example check the questionnaire.log file for LaTeX compile errors.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/usr/local/lib/python3.5/dist-packages/sdaps/cmdline/setup.py", line 45, in setup
    return setuptex.setup(cmdline['project'], cmdline['questionnaire.tex'], cmdline['additional_questions'], cmdline['add'])
  File "/usr/local/lib/python3.5/dist-packages/sdaps/setuptex/__init__.py", line 108, in setup
    raise AssertionError('PDF file not generated')
AssertionError: PDF file not generated

**Comment by pantzO** [comment]
By the way, thanks for the more than fast reply (even if upgrading did not helped much).

**Comment by benzea** [comment]
Uhm, you have read the message?

! Package sdaps Error: Sorry, there is no help text for the checkmode you have
choosen right now! Please pass the noinfo optional argument to the questionnair
e environment!.

You just need to use

    \begin{questionnaire}[noinfo]

rather than

    \begin{questionnaire}[noinfo]

**Comment by pantzO** [comment]
It works like a charm !

Sorry... I should have read the message to the end...
and tried to pass the "noinfo" option as said.

Still I find the behavior somehow odd. From my point of view it would be more natural if the "info" where modified accordingly to the check mode chosen.

Anyway, sdaps is a great tool (in particular compared to other "similar applications").

Thanks a lot !

**Comment by benzea** [comment]
Oh, fully agree! It was simply never a priority on my part to do this and was then forgotten.

It should be quite straight forward to do. Hardest part is coming up with the English strings. So maybe it would make sense to actually leave this bug open (rewording the title) so that this can be addressed in the future.

**Comment by pantzO** [comment]
OK... I've reopened the issue and changed the title. I guess it could help  anyone stumbling on the same issue and work as a reminder if you find some spare time to fix it... even if you seem to have a lot on your plate already.

Anyway, Thanks again !

**Comment by benzea** [comment]
Hrm, there is now issue #154, doesn't really matter which one is open and closing this one.
