### ISSUE TITLE
SyntaxError: invalid syntax 

### ISSUE THREAD

**Issue by hmkim** [sdaps/sdaps#133]
Hello,

First, thanks for your nice app (sdaps).

I installed the sdaps  via apt in Ubuntu.

and When I try to setup with odt file format, I got the error in below.
```

Traceback (most recent call last):
  File "/usr/local/bin/sdaps", line 23, in <module>
    sys.exit(sdaps.main())
  File "/usr/local/lib/python2.7/dist-packages/sdaps/__init__.py", line 64, in main
    return cmdline['_func'](cmdline)
  File "/usr/local/lib/python2.7/dist-packages/sdaps/cmdline/setup.py", line 92, in setup
    from sdaps import setupodt
  File "/usr/local/lib/python2.7/dist-packages/sdaps/setupodt/__init__.py", line 36, in <module>
    from . import boxesparser
  File "/usr/local/lib/python2.7/dist-packages/sdaps/setupodt/boxesparser.py", line 19, in <module>
    from pdftools import *
  File "/usr/local/lib/python2.7/dist-packages/pdftools/__init__.py", line 15, in <module>
    from pdftools.pdftools import (  # noqa: F401
  File "/usr/local/lib/python2.7/dist-packages/pdftools/pdftools.py", line 16
    def pdf_merge(inputs: [str], output: str, delete: bool = False):
                        ^
SyntaxError: invalid syntax

```

$ sdaps /tmp/project setup --duplex temp1.odt temp1.pdf

How can I solve this problem ?

**Comment by hmkim** [comment]
Thank you for your reply.

After remove the python-pdftools, I ran the command again.

and I have an new error.

> ------------------------------------
> If the dependencies for the "annotate" command are installed, then an annotated version will be created next to the original PDF file.
> ------------------------------------
> /usr/local/lib/python2.7/dist-packages/sdaps/annotate/__init__.py:18: PyGIWarning: Poppler was imported without specifying a version first. Use gi.require_version('Poppler', '0.18') before import to ensure that the right version gets loaded.
>   from gi.repository import Poppler
> /usr/local/lib/python2.7/dist-packages/sdaps/annotate/buddies.py:21: PyGIWarning: Pango was imported without specifying a version first. Use gi.require_version('Pango', '1.0') before import to ensure that the right version gets loaded.
>   from gi.repository import Pango
> /usr/local/lib/python2.7/dist-packages/sdaps/annotate/buddies.py:22: PyGIWarning: PangoCairo was imported without specifying a version first. Use gi.require_version('PangoCairo', '1.0') before import to ensure that the right version gets loaded.
>   from gi.repository import PangoCairo
> Traceback (most recent call last):
>   File "/usr/local/bin/sdaps", line 23, in <module>
>     sys.exit(sdaps.main())
>   File "/usr/local/lib/python2.7/dist-packages/sdaps/__init__.py", line 64, in main
>     return cmdline['_func'](cmdline)
>   File "/usr/local/lib/python2.7/dist-packages/sdaps/cmdline/setup.py", line 100, in setup
>     return setupodt.setup(survey, cmdline['questionnaire.odt'], cmdline['questionnaire.pdf'], cmdline['additional_questions'], cmdline)
>   File "/usr/local/lib/python2.7/dist-packages/sdaps/setupodt/__init__.py", line 88, in setup
>     qobjectsparser.parse(survey, questionnaire_odt, boxes)
>   File "/usr/local/lib/python2.7/dist-packages/sdaps/setupodt/qobjectsparser.py", line 102, in parse
>     xml.sax.parseString(content, handler)
>   File "/usr/lib/python2.7/xml/sax/__init__.py", line 49, in parseString
>     parser.parse(inpsrc)
>   File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
>     xmlreader.IncrementalParser.parse(self, source)
>   File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
>     self.feed(buffer)
>   File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
>     self._parser.Parse(data, isFinal)
>   File "/usr/lib/python2.7/xml/sax/expatreader.py", line 317, in start_element
>     self._cont_handler.startElement(name, AttributesImpl(attrs))
>   File "/usr/local/lib/python2.7/dist-packages/sdaps/setupodt/qobjectsparser.py", line 66, in startElement
>     self.answer.setup.box(self.boxes.pop(0))
> IndexError: pop from empty list
> 

Could you explain about this problem?

**Comment by benzea** [comment]
Yeah, that means it didn't find the boxes in the PDF or not enough boxes.

There should be more output (i.e. the detected structure), which might give you an idea what is going on.

**Comment by hmkim** [comment]
I modified the example data a bit and export to pdf.

but with this pdf, I always had an error.

With example PDF and ODF, I have no error.

Could you explain what option must apply when  I  exporting PDF?

<img width="1440" alt="2018-06-21 22 06 37" src="https://user-images.githubusercontent.com/4966343/41720975-96325e0c-759f-11e8-925c-d226c2dcc080.png">

**Comment by benzea** [comment]
Probably your Libreoffice is just too new and generates a different file that is incompatible.

Are you using https://launchpad.net/~benjamin-sipsolutions/+archive/ubuntu/sdaps, if not, can you try that?

Other than that, I the libreoffice support is currently scheduled to be dropped with the next major release, which should happen some time later this year.

**Comment by benzea** [comment]
Also, you are still running SDAPS from a local copy rather than the version installed through apt.

**Comment by hmkim** [comment]
I understand the fact (drop for libreoffice support in SDAPS).

Ok. I removed all local copy of SDAPS.
and I installed the fresh copy of SDAPS through apt using  https://launchpad.net/~benjamin-sipsolutions/+archive/ubuntu/sdaps.

I got the error in below.
<img width="1123" alt="2018-06-21 23 56 51" src="https://user-images.githubusercontent.com/4966343/41727273-e45e7a2a-75ae-11e8-90dc-a3b6fa703ade.png">
<img width="868" alt="2018-06-21 23 56 42" src="https://user-images.githubusercontent.com/4966343/41727274-e49eeb46-75ae-11e8-9d79-db94cbba6415.png">

**Comment by benzea** [comment]
Hm, now you are running a local git checkout of master. The test is failing because you are missing the tex/class submodule. i.e. you need to run:

    git submodule init
    git submodule update

Though that version does **not** support libreoffice anymore.

**Comment by benzea** [comment]
btw. the reason to drop LibreOffice is that it is hard to support due to the lack of python3 ports for different dependencies.

The other reason is that it is kinda hard to use because obscure errors can happen if the formatting is not exactly as expected.

**Comment by benzea** [comment]
Actually, I just realised that it might also be that you simply have not build the LaTeX class (./setup.py build).

**Comment by hmkim** [comment]
> Hm, now you are running a local git checkout of master. The test is failing because you are missing the tex/class submodule. i.e. you need to run:

No, I'm not running a local git checkout of master. 
Just I used the test data in local git checkout of master.

**Comment by hmkim** [comment]
I ran a local git of sdaps-class checkout of master.
$ cd sdaps-class
$ ./build.lua install

$ kpsewhich -var-value=TEXMFHOME
/home/parallels/texmf

I successfully pass the command in above , but now I debugging for other error in below.

<img width="1066" alt="2018-06-22 22 43 22" src="https://user-images.githubusercontent.com/4966343/41779724-aeadec5c-766d-11e8-96eb-4b6756525c26.png">

**Comment by benzea** [comment]
Yes, you are if you run "./run-test-locally.sh' rather than './run-test.sh'

No, it does not. I changed "setup" to be an alias for "setup_tex" with the removal of ODT support.
