### ISSUE TITLE
What kind of algorithms are used in SDAPS? :)

### ISSUE THREAD

**Issue by dikey94** [sdaps/sdaps#136]
Hi there :)
I'm going to use SDAPS in my university project. I'd like to know how SDAPS works internally. 

Thanks.

**Comment by benzea** [comment]
I am not sure you want to know ;-)

For the correction matrix, it is some really convoluted code that tries to find the lines and follow them. For some reason it work, I am not sure how (and no, this is not something like hough transformation).

For the checkboxes:
 * Basically, find the exact location using a correlation (just the best match for the exact location)
 * Find the overall coverage
 * Find lines using hough transformation, wipe one out, repeat 3 times, then calculate coverage
 * Find empty spaces above a certain size, I think

For textboxes:
 * Just coverage check in a 2x2mm area (IIRC) overlapping by 1x1mm, if coverage is above a threshold, consider it checked.
 * I think there is some dirt removal (discard anything below 0.5mmx0.5mm or so)

**Comment by dikey94** [comment]
My task is quite simple - I have to write a description of any algorithm used in SDAPS in a kind of... scientific way :)

**Comment by benzea** [comment]
Have a look at:
 * "boxgallery" command output with `--debugrecognition` option
 * If you feel courageous:
   * sdaps/image/*.c (wrap_image.c is boring)
   * sdaps/recognize/buddies.py

The values from the 3 metrics for checkboxes are applied using an extremely simple mapping.

**Comment by benzea** [comment]
Maybe you can contribute a description in some form? ;-)

**Comment by benzea** [comment]
Note that a surprising chunk of code is low level image loading and bit counting, which I optimised manually in 2009 or so to run on my powerbook back … (yay for POWER CPUs)

Probably a lot of that could be done much better in other ways … but I guess you can simply ignore that.

**Comment by dikey94** [comment]
I'm not a Python/C expert but I will try

**Comment by benzea** [comment]
Closing this issue. I would be happy to merge some documentation about the algorithms, but I don't think it is a priority and I don't see much of a value right now. It is interesting, but just not relevant for most people.
