### ISSUE TITLE
Translating to Sinhala.

### ISSUE THREAD

**Issue by Menuka5** [sdaps/sdaps#143]
Dear Admins,
I would like to help to translate Sdaps into Sinhala which is my native Language. I visited https://hosted.weblate.org/projects/sdaps/master/ But I can't see an option to add the Sinhala Translation. Can you add it? 
I would very much like to help.
Thank you :smile:

**Comment by benzea** [comment]
You can actually make a requset on hosted.weblate.org, but in the end it needs to be manually added anyway, so this is as good :)

**Comment by benzea** [comment]
I also added the language for LaTeX with Sinhala as the dictionary name. I am not quite sure if this works. It could be that the LaTeX translations are unusable for you or that the language name needs to be changed.

**Comment by Menuka5** [comment]
I checked it. Seems working fine :smiley: 
Thank you for adding Sinhala :+1:
