### ISSUE TITLE
AttributError: paper_width

### ISSUE THREAD

**Issue by ntala** [sdaps/sdaps#146]
Hello,
I am using sdaps 1.9.3-2 and I can't get my survey to be set up because the command sdaps project setup (or setup_tex) document.tex is raising the error : AttributError: paper_width
This problem seems to occure from the function : survey.calculate_survey_id().

I am going to try other versions but I would really appreciate any solution.

Have a nice day.

**Comment by benzea** [comment]
You need to wrap everything into an \begin{questionnaire}/\end{questionnaire} block. That will solve the issue.

**Comment by ntala** [comment]
Oops !
Thank you for your answer. I am sorry to have omitted this "classical tag".
