### ISSUE TITLE
Allow overriding the LaTeX engine command (during setup)

### ISSUE THREAD

**Issue by benzea** [sdaps/sdaps#150]
We currently use `pdflatex` by default. We could switch the default to `xelatex`, but also other engines may be useful. Also, `pdflatex` generates a more stable output, which is kinda nice.

Anyway, I am thinking we should allow passing the LaTeX command to call on the command line of the `setup` command.

**Comment by benzea** [comment]
Yeah, modify defs.py and change the value of `latex_engine` from `pdflatex` to `xelatex`.

**Comment by omidraha** [comment]
To modify `defs.py`, and also install some other related packages, I create a new docker file:

```
FROM ubuntu:18.04  
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:benjamin-sipsolutions/sdaps
RUN apt-get update
#RUN apt-get install texlive-xetex -y
#RUN apt-get install texlive-lang-arabic -y
RUN apt-get install -y sdaps
RUN apt-get install vim -y
RUN echo "latex_engine = 'xelatex'" >> /usr/lib/python3/dist-packages/sdaps/defs.py
WORKDIR "/workdir"
ENTRYPOINT ["sdaps"]
```

But now I get this error (even when `latext_engine` is set to `pdflatex`) for `setup_tex` command:

```
! LaTeX Error: File `sdaps.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.7 \usepackage
               [utf8]{inputenc}^^M 
```
Do you know what's wrong with this docker file?

**Comment by benzea** [comment]
Nothing.

You upgraded to the "unstable" SDAPS version, which contains a new LaTeX class, so you need to make a few modifications.

 * Replace `sdaps` with `sdapsclassic`
 * Pass [cols=X] to choicequestion rather than just [X]

**Comment by omidraha** [comment]
But in the docker file even if I change this line:

`RUN add-apt-repository ppa:benjamin-sipsolutions/sdaps`

to this line, to have stable version:

`RUN add-apt-repository ppa:benjamin-sipsolutions/sdaps-stable`

I get the same error.

What's the ppa stable address?
How can i find the current installed version? there is no `sdaps --version` command.
Anyway fixed with replacing `sdaps` with `sdapsclassic` as you said.

After that I also have `UnicodeDecodeError` error:
```
------------------------------------
Error: An error occured in the setup routine. The survey directory still exists. You can for example check the questionnaire.log file for LaTeX compile errors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/setup.py", line 45, in setup
    return setuptex.setup(cmdline['project'], cmdline['questionnaire.tex'], cmdline['additional_questions'], cmdline['add'])
  File "/usr/lib/python3/dist-packages/sdaps/setuptex/__init__.py", line 115, in setup
    sdapsfileparser.parse(survey)
  File "/usr/lib/python3/dist-packages/sdaps/setuptex/sdapsfileparser.py", line 56, in parse
    sdaps_data = sdaps_file.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 10: ordinal not in range(128)
```

Fixed by adding this line to docker file:

```Dockerfile
# set locale to utf8
RUN apt-get install -y locales
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
```

**Comment by benzea** [comment]
Sorry about that :(

The old stable series has quite a lot of issues, and the goal currently is to push out 2.0 "quickly" (right now I suspect start of next year). The decision was made to push the usage of the unstable release, which is why both PPA repositories have the unstable version currently.

There may be old builds for older ubuntu versions. It could work to explicitly pick those versions.
