### ISSUE TITLE
Add questionnaire instructions for alternative checkmode option values (fill/check)

### ISSUE THREAD

**Issue by omidraha** [sdaps/sdaps#154]
When  I uncomment and change this [line](https://github.com/sdaps/sdaps/blob/master/examples/example.tex#L23) to

`  checkmode=check,`

I get this error:
```
! Package sdaps Error: Sorry, there is no help text for the checkmode you have 
choosen right now! Please pass the noinfo optional argument to the questionnair
e environment!.
```

To fix the error, I try to change this [line](https://github.com/sdaps/sdaps/blob/master/examples/example.tex#L41) to:
```
\begin{questionnaire}[noinfo]
```

But now,  there is no any detected answer on the pdf result file.

It's same for `fill` option, and the `checkmode` option only work with this option:

```
  checkmode=checkcorrect, 
```

**Comment by benzea** [comment]
> But now, there is no any detected answer on the pdf result file.

What do you mean? If you add `[noinfo]` then the instructions at the top of the first page will be removed. Are you seeing something else?

**Comment by omidraha** [comment]
I mean after change ` checkmode=check,` option on the `example.tex` file,  and then run `add`,  `recognize` and `report`commands for the same input files on this [issue](https://github.com/sdaps/sdaps/issues/151#issuecomment-436287606), no  answer has been detected on the `report_1.pdf` result file.
But when I change option to `checkmode=checkcorrect, `, answers detected on the `report_1.pdf` result file.

**Comment by benzea** [comment]
Yeah, it is a completely different questionnaire after that change. You need to start from scratch and print the questionnaire again.

**Comment by benzea** [comment]
While at it, I changed the strings a bit.

What do people think of the following three versions:

![screenshot from 2018-12-16 15-11-48](https://user-images.githubusercontent.com/55234/50054720-1a78b400-0145-11e9-9239-c55ab01db090.png)
![screenshot from 2018-12-16 15-12-16](https://user-images.githubusercontent.com/55234/50054721-1b114a80-0145-11e9-8f62-10ec4dd64f14.png)
![screenshot from 2018-12-16 15-12-49](https://user-images.githubusercontent.com/55234/50054722-1b114a80-0145-11e9-8b0f-2ada3028e678.png)

**Comment by benzea** [comment]
It was suggested to increase the spacing a bit. Right now it is \quad + the normal column spacing; I guess I'll just add a bit more and commit it then.

**Comment by benzea** [comment]
Alright, this is what is going to go in now:

![screenshot from 2018-12-26 19-05-43](https://user-images.githubusercontent.com/55234/50453527-76132080-0941-11e9-9bd8-5fb727173e1b.png)
![screenshot from 2018-12-26 19-06-07](https://user-images.githubusercontent.com/55234/50453528-76132080-0941-11e9-9676-c84785d1a98f.png)
![screenshot from 2018-12-26 19-06-29](https://user-images.githubusercontent.com/55234/50453529-76abb700-0941-11e9-9686-8d44340c1676.png)
