### ISSUE TITLE
The checkboxstyle with ellipse option not work with choicequestion

### ISSUE THREAD

**Issue by omidraha** [sdaps/sdaps#155]
This tag `\def\checkboxstyle{ellipse}` has no effect for `choicequestion`, the checkbox shows as box and not as radio box.

This is `example.tex` file:

```
\documentclass[
english,
checkmode=check,
pagemark,
stamp]{sdapsclassic}
\usepackage[utf8]{inputenc}
\usepackage{multicol}

\author{The Author}
\title{The Title}

\def\checkboxstyle{ellipse}

\begin{document}
    \begin{questionnaire}[noinfo]
        \begin{info}
            Some information here. Nothing special, just adds a line above/below.
        \end{info}
        \addinfo{Date}{10.03.2013}
        \section{Range Questions}
        \begin{choicequestion}[cols=3]{Which of the following Open Source
        Optical Mark Recognition software
        packages have you heard about?}
            \choiceitem{SDAPS}
            \choicemulticolitem{2}{Auto Multiple Choice}
            \choiceitem{QueXF}
        \end{choicequestion}
    \end{questionnaire}
\end{document}

```

This is docker file used:

```Dockerfile
FROM ubuntu:18.04  
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:benjamin-sipsolutions/sdaps-stable
RUN apt-get update
RUN apt-get install texlive-xetex -y
RUN apt-get install texlive-lang-arabic -y
RUN apt-get install -y sdaps
RUN apt-get install vim -y
RUN echo "latex_engine = 'xelatex'" >> /usr/lib/python3/dist-packages/sdaps/defs.py
# set locale to utf8
RUN apt-get install -y locales
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
WORKDIR "/workdir"
ENTRYPOINT ["sdaps"]
```

This is ([questionnaire.pdf](https://github.com/sdaps/sdaps/files/2599837/questionnaire.pdf))  output file.
As you can see check box style is box and not ellipse on the pdf file.

I don't have this problem with [this](https://github.com/sakalauskas/docker-sdaps) one docker file.

**Comment by benzea** [comment]
Ah, yes … the \def\checkboxstyle thing will not work with the new class. On the other side, any question where only one choice is possible, will get the ellipse/round style while multiple choice questions get the square style by default.

Right now, to change it you can do:
```
\ExplSyntaxOn
\sdaps_context_set:n { * = { ellipse } }
\ExplSyntaxOff
```

Or, more specifically, to just change the default for the multiple choice questions:
```
\ExplSyntaxOn
\sdaps_context_set:n { multichoice = { ellipse } }
\ExplSyntaxOff
```

We probably need a new command to allow changing this more easily. But I would like to understand the usecases a bit better before doing so.

**Comment by benzea** [comment]
Ah, have a look at:
  https://sdaps.org/class-doc/sdapsclassic.html

There are also the `optionquestion` and `optiongroup` environments now. Or you can also pass the `singlechoice` option to the `choicequestion` and `choicegroup` questions for the same effect.

**Comment by omidraha** [comment]
Thanks, I was [stuck](https://github.com/sdaps/sdaps/issues/145) on old [docs](https://sdaps.org/LaTeX/).

**Comment by benzea** [comment]
Btw. the support for RTL is rather new in 1.9.4. So if you see anything even slightly weird, I would be happy to hear about it.

**Comment by benzea** [comment]
Hmm, I think that the support for single choice questions is generally good enough. We should probably improve the override support, but that seems beyond the scope of this ticket.

Closing for now. If you care a lot about making this simpler, then please open an issue against sdaps-class. I guess we could add a nicer example and we can also add a command that doesn't require the use of `\ExplSyntaxOn/\ExplSyntaxOff`.

**Comment by ysalmon** [comment]
It would be nice if the example included with sdaps did not contain this outdated command.
