### ISSUE TITLE
Detection of selection boxes with offset

### ISSUE THREAD

**Issue by IoAg** [sdaps/sdaps#157]
Hello,

I have a a weird behaviour which I could not explain. When I run the recognise on sdaps and then visualize the results in the GUI the detected boxes are offset only in one of the two pages of the questionnaire. But when I ran annotate the box position is marked correctly (see attachments). I also played around with _questionnaire.sdaps_ but it seems that it is not used in the recognition process. My sdaps version is 1.9.1.

I have also seen this topic #95, but in that case the detection is correct and only the rendering offset.

Do you have any idea/explanation about this behaviour?

Thanks in advance,
Ioannis

![screenshot_sdaps_gui](https://user-images.githubusercontent.com/28091775/48781369-2d31d180-ecdc-11e8-874a-378e283ee65d.png)
![screenshot_sdaps_annotated](https://user-images.githubusercontent.com/28091775/48781350-22773c80-ecdc-11e8-8de7-bbf021471700.png)

**Comment by benzea** [comment]
Now that is **weird**.

OK … I see what happened. If you look at the annotation, the annotated version the content is much lower. It looks like everything below the page header was moved up. And, to be honest, that is impossible without the survey id (i.e. the QR code) changing.

If I had to guess what happened, then my guess is that someone actually edited the PDF manually before printing it …

**Comment by IoAg** [comment]
I see your point. But on the other hand I don't think somebody changed the PDF because all the fields in the second page (I don't display it here) are detected correctly.

Do you have any idea of how to shift the fields up during detections? I want to avoid going through all of the questionnaires manually ;)

**Comment by benzea** [comment]
Funky, maybe the PDF reader or printer rendered it wrong?

Is it a lot of them? It will require some ugly hacks to do it … the easiest might be to increase/shift the search area for checkboxes if they are on the first page.

So, something like:
https://gist.github.com/benzea/2c0481db5855ac45b3e1e2c98095facc

**Comment by IoAg** [comment]
Thank you for the suggestion. I will try it out and try to do the same for the whole 1st sheet too.

I will post back when I have some results.
