### ISSUE TITLE
Layouter=rotated  : angle argument

### ISSUE THREAD

**Issue by jdanion** [sdaps/sdaps#159]
Hello everyone,

I'm new to this project. I find it awesome. I plan to use it for medical synoptic report purpose with our home made EMR.

In order to minimize the place used for headers (i need to use multicol very often), i would like to be able to specify the rotating angle for choicegroup headers.

For the moment i found in sdapsarray.ctx .  line 381

 **\box_rotate:Nn \l_tmpa_box { 70 }**

i can manually change to

 **\box_rotate:Nn \l_tmpa_box { 33 }**

for example 

but i'm sur there is a better, more elegant and customisable way to make it

like 

\begin{choicegroup}[layouter=rotated,**angle=70**, etc]

Can someone have a clue to help me ?

And thanks again for this wonderful project, I really intend to convince our hospital IT department to implement it.

**Comment by benzea** [comment]
Ah, that should be simple to implement. Do you feel up to working on it or should I just do it?

I can quite quickly implement it, mostly asking if you are interested to do it as a learning experience in LaTeX/plain TeX :)

**Comment by jdanion** [comment]
Well, I only recently managed to run SDAPS natively on macOS, (I first used a Ubuntu VM until now).
I would be very interested, but I'm really completely new to LaTeX (I chose another job that diverts me from development since high school, I also had to give up linux for several years to devote time to medicine, hopeffuly, i'm now nearly graduated and i have some work time dedicated to improvements in patient care and SDAPS is a very interesting tool!). 

I feel comfortable hacking and understanding how to code, but I'm sure it would result in a bad / bad solution if I try to implement it alone. 

In fact i found something that will be difficult for me, it is that this implement will need to change sdapsarray.dtx each time a new sdaps setup "project" is made (maybe quite easy when you know how to do the job, but difficult when your are only a hobbyist)

**Comment by benzea** [comment]
Well, we obviously just patch the upstream sdapsarray.dtx file to add the option :)

As I said, quite straight forward for me. I'll plan to look into it some time this week, please ping me if I don't get around to do that.

**Comment by jdanion** [comment]
Okay, I look forward to your patch, and I'm sure I'll find a lot of other cool stuff to add (like a "model" stamped possibility with pre-marked responses based on previously recognized questionnaries, but i need to further study how it works :) ). I have a lot of other ideas but maybe I should wait for SDAPS 2.0 because some features are probably planned there.

**Comment by benzea** [comment]
Pre-filling already works in theory ;-)

In practice, there is no good way of using it though.

**Comment by benzea** [comment]
Hi, experimented with a quick proper implementation:

https://p.sipsolutions.net/37d16f57b7978d9e.txt

The sizing calculation is a bit dumb though, and things will fall appart for smaller angles. But that is probably alright.

**Comment by benzea** [comment]
Pushed it to sdaps-class, it will be available in the next release (1.9.5).
