### ISSUE TITLE
Updating SDAPS to newest version

### ISSUE THREAD

**Issue by Anurangi** [sdaps/sdaps#161]
I used a previous version of SDAPS till now and I want to update it to 1.9.4.But when I try to install it it says that I already have the latest version of SDAPS.And it also says that setup.py directory is not there.Any documentation to ease the process of updating SDAPS?

**Comment by benzea** [comment]
Could you be more specific as to what you did to upgrade?

**Comment by Anurangi** [comment]
Hi I removed sdaps using the command sudo apt-get remove sdaps.This did not remove the software correctly it seems.
Later I installed sdaps again using the commands 
 sudo add-apt-repository ppa:benjamin-sipsolutions/sdaps
sudo apt-get update
sudo apt-get install sdaps 

The result is the same sdaps version I had earlier which is 1.9.1-1.

**Comment by benzea** [comment]
Right, then the problem is simply that the package was only build for
Ubunutu Bionic and not Xenial.

That is fixable (i.e. just need to upload it again against the older
distribution).

**Comment by benzea** [comment]
I just submitted a xenial build. Maybe that will work (I'll reopen if it doesn't). Note that I am not sure whether I will reliably provide such builds in the long run.

**Comment by Anurangi** [comment]
Thank you I’ll give it a try

**Comment by agmira** [comment]
Hello. I'm using "ppa:benjamin-sipsolutions/sdaps" in Ubuntu Xenial, and I think I still have the same problem. My command order is like older versions: "sdaps <project-folder> <command>" 
I have also ubuntu Bionic, and all is OK. My command order is "sdaps <command> <project-folder>". If we search build status for Xenial release in launchpad.net, it is saying there were problems. Is it possible to solve them? Thanks.

**Comment by benzea** [comment]
Looks like Ubuntu Xenial does not have `python3-opencv`. While one could fix things up to build, it means that the `convert` feature cannot be supported on this old distributions.

So, my guess it is not worth the effort. Sorry about that.

**Comment by agmira** [comment]
Hi!!. Ok, you are right. So I'll continue using Bionic. Thank you for your help and great job!
