### ISSUE TITLE
Assertion errors during setup: question IDs and page numbers

### ISSUE THREAD

**Issue by stimon** [sdaps/sdaps#163]
I had a working questionnaire until I tried to alter the structure, simply moving a section further in the questionnaire makes the setup routine to throw assertion errors:
```
Error: Caught an Exception while parsing the SDAPS file. The current state is:
<sdaps.model.questionnaire.Questionnaire object at 0x7ffa6175ee10>
------------------------------------
Error: An error occured in the setup routine. The survey directory still exists. You can for example check the questionnaire.log file for LaTeX compile errors.
Traceback (most recent call last):
  File "/home/sdaps/.local/lib/python3.5/site-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/home/sdaps/.local/lib/python3.5/site-packages/sdaps/cmdline/setup.py", line 45, in setup
    return setuptex.setup(cmdline['project'], cmdline['questionnaire.tex'], cmdline['additional_questions'], cmdline['add'])
  File "/home/sdaps/.local/lib/python3.5/site-packages/sdaps/setuptex/__init__.py", line 115, in setup
    sdapsfileparser.parse(survey)
  File "/home/sdaps/.local/lib/python3.5/site-packages/sdaps/setuptex/sdapsfileparser.py", line 144, in parse
    survey.questionnaire.add_qobject(qobject, new_id=index)
  File "/home/sdaps/.local/lib/python3.5/site-packages/sdaps/model/questionnaire.py", line 67, in add_qobject
    assert new_id > self.last_id
AssertionError
```
or 
```
Error: Caught an Exception while parsing the SDAPS file. The current state is:
<sdaps.model.questionnaire.Questionnaire object at 0x7febdfa8fe10>
------------------------------------
Error: An error occured in the setup routine. The survey directory still exists. You can for example check the questionnaire.log file for LaTeX compile errors.
Traceback (most recent call last):
  File "/home/sdaps/.local/lib/python3.5/site-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/home/sdaps/.local/lib/python3.5/site-packages/sdaps/cmdline/setup.py", line 45, in setup
    return setuptex.setup(cmdline['project'], cmdline['questionnaire.tex'], cmdline['additional_questions'], cmdline['add'])
  File "/home/sdaps/.local/lib/python3.5/site-packages/sdaps/setuptex/__init__.py", line 118, in setup
    qobject.setup.setup()
  File "/home/sdaps/.local/lib/python3.5/site-packages/sdaps/setup/buddies.py", line 107, in setup
    self._box(box)
  File "/home/sdaps/.local/lib/python3.5/site-packages/sdaps/setup/buddies.py", line 93, in _box
    assert self.obj.page_number == box.page_number
AssertionError
```

This happens only altering the structure, like commenting out an `optiongroup`, so I don't think it makes sense for it to happen. 

What can be the cause and how can I fix it?

Thanks

**Comment by benzea** [comment]
Hmm, right …

I think the core program doesn't support it if a question crosses a page boundary. Could that be the cause?

**Comment by stimon** [comment]
That could be the cause for the `page_number` check. With my """tests""" it doesn't happen so much. 
But I'm unable to get rid of the QObject id issue. Do you think it is also because of page boundaries?? 
I guess that forcing with `\newpage` ought to solve it in that case, right?

**Comment by benzea** [comment]
Hmm, no, the ID issue seems like something else. Which version are you using? Could you attach a failing example document?

I kind of think I might have fixed a bug like this, but I am unsure right now.

**Comment by stimon** [comment]
Oh, it actually seems that forcing new pages works. A bit odd though. This has happened with both current and previous versions. 
I'm gonna keep trying to see if I manage to get the full questionnaire. 

A good new feature would be a bit of extra info when SDAPS fails, like logging how far it got while parsing/generating the objects. It is tricky to find where the errors are, especially with very long questionnaires.

**Comment by stimon** [comment]
Managed to have the questionnaire working again. Explicit `\newpage` before problematic items did the trick. 

I repeat myself to say that it would be good that SDAPS states the object causing the error. It is very time-consuming to find out by trial and error.

**Comment by benzea** [comment]
Hm, I think what we used to do for the libreoffice code was dump out the current state of the questionnaire on a failure. That would show you the last processed question basically.

**Comment by benzea** [comment]
Oh … this is just a simple regression in the python 3 port:

Rather than
```
<sdaps.model.questionnaire.Questionnaire object at 0x7febdfa8fe10>
```

Well, that was easy. A simple regression introduced when SDAPS was ported to python3.

**Comment by stimon** [comment]
Will try the fix, Thanks Benjamin.

**Comment by stimon** [comment]
Hi, I'm reopening this issue because it happened again. 
This is a small sample of what I'm using:
```latex
\ExplSyntaxOn
\let\mysetcheckboxtype\sdaps_checkbox_set_type:n
\let\qbegin\sdaps_qobject_begin:nnn
\let\mycheckbox\sdaps_checkbox:nn
\let\myanswer\sdaps_answer:n
\let\qend\sdaps_qobject_end:n
\let\mytextbox\sdaps_textbox_hstretch:nnnnn

\title{CRF - Clinical Report Form - Baseline \crfversion}

\begin{document}

  \begin{questionnaire}

% New front page
      \begin{center}
           \Huge \textbf{A big title}
      \end{center}


      Studienr HUK
      \qbegin{huk}{Text}{huk}
        \mytextbox{HUK_1}{3mm}{7mm}{7mm}{0}
        \mytextbox{HUK_2}{3mm}{7mm}{7mm}{0}
        \mytextbox{HUK_3}{3mm}{7mm}{7mm}{0}
        \mytextbox{HUK_4}{3mm}{7mm}{7mm}{0} .
        \mytextbox{HUK_5}{3mm}{7mm}{7mm}{0}
      \qend{huk}

      \begin{optionquestion}[cols=1, var=test]{testing}
    		\choiceitem[val=1]{Yes}
    		\choiceitem[val=0]{No}
    	\end{optionquestion}
%rest of the document
```

After it finishes the PDF generation, it fails:
```
Error: Caught an Exception while parsing the SDAPS file. The current state is:
Questionnaire
1(Text) huk {1}
        0(Textbox )  37.7  60.2   7.0  10.0
        1(Textbox )  45.7  60.2   7.0  10.0
        2(Textbox )  53.8  60.2   7.0  10.0
        3(Textbox )  61.9  60.2   7.0  10.0
        4(Textbox )  72.3  60.2   7.0  10.0
 
------------------------------------
Error: An error occured in the setup routine. The survey directory still exists. You can for example check the questionnaire.log file for LaTeX compile errors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 67, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/setup.py", line 55, in setup
    cmdline['add'])
  File "/usr/lib/python3/dist-packages/sdaps/setuptex/__init__.py", line 116, in setup
    sdapsfileparser.parse(survey)
  File "/usr/lib/python3/dist-packages/sdaps/setuptex/sdapsfileparser.py", line 148, in parse
    survey.questionnaire.add_qobject(qobject, new_id=index)
  File "/usr/lib/python3/dist-packages/sdaps/model/questionnaire.py", line 71, in add_qobject
    assert new_id > self.last_id
AssertionError
```
A couple of things to note:
* If I remove the problematic textboxes it finishes the setup, despite I use this command in similar fashions multiple times through the questionnaire
* It is in the very beginning, so there is no question jumping across pages. 

What could be causing this id issue?

Thanks!

**Comment by benzea** [comment]
Not sure, could you attach the full file that produces the error and ideally also the generated `questionnaire.sdaps` file (or `FILENAME.sdaps` if you compile it elsewhere and the .tex file is named differently)?

**Comment by stimon** [comment]
[sdaps.zip](https://github.com/sdaps/sdaps/files/5623207/sdaps.zip)
Here are the tex and .sdaps files :)

**Comment by benzea** [comment]
Right, there is an interaction issue with the `sdapsclassic` class. I don't think it is fixable really (well, it could error out, so maybe that is a good idea). Basically, the first question tries to insert a dummy header/section with ID zero. To do that, it subtracts one from the counter, which has been increased already due to the question. That causes the collosion.

Just add the following right at the start for now:
```
\ExplSyntaxOn
\sdaps_classic_ensure_section:
\ExplSyntaxOff
```

Or:
 * Have a "normal" question from the `sdapsclassic` set the start
 * Add a `\section` in front

(Well, it now fails after `21.7(Text) amypet_comment {31}`, but that is something different.)

**Comment by stimon** [comment]
Great! adding the `\section` does the trick. 
However, I just upgraded to 1.9.9 and `\question` as headers provoke `! Undefined control sequence` errors. I don't know if that is supposed to happen now.

**Comment by benzea** [comment]
> However, I just upgraded to 1.9.9 and \question as headers provoke ! Undefined control sequence errors.

What do you mean with that? Is that a specific use case inside a group of questions?

**Comment by stimon** [comment]
I was using (most probably wrongly) `\question` command to produce the number header for arbitrary content. Like this:
```latex
\let\mysetcheckboxtype\sdaps_checkbox_set_type:n
\let\qbegin\sdaps_qobject_begin:nnn
\let\mycheckbox\sdaps_checkbox:nn
\let\myanswer\sdaps_answer:n
\let\qend\sdaps_qobject_end:n
\let\mytextbox\sdaps_textbox_hstretch:nnnnn
\ExplSyntaxOn
\newcommand{\writtendigits}[2]{
    \color{orange}
    \qbegin{writtendigits}{Text}{}
      \int_step_inline:nnnn { 1 } { 1 } { #2 } { \mytextbox{#1_##1}{3mm}{7mm}{7mm}{0}  \int_compare:nT { ##1 < #2 } { ~ } }
    \qend{writtendigits}
    \color{black}
}
\ExplSyntaxOff

\question{Some question header}
% this renders n textboxes that we use for handwritten digits
\writtendigits{bar}{2}
```

On 1.9.8 it would render the proper `0.1 Some question header`, now it fails. 

I'm sure I'm doing this wrong, is there a correct way to generate question headers for custom layouts/elements? 

Thanks!
