### ISSUE TITLE
Error using \immediate\write\sdapsoutfile{\unexpanded{STRING}} command for custom layout

### ISSUE THREAD

**Issue by sorXCode** [sdaps/sdaps#171]
I am trying to create a custom layout and the documentation pointed to use `\immediate\write\sdapsoutfile{\unexpanded{STRING}}` to write out metadata data manually, but I keep getting "undefined control sequence" error whenever I try to build the latex. I have tried using `\immediate\write\sdapsclassicoutfile{\unexpanded{STRING}}` but still got the same error. Is there anyway to fix this or alternative way to create custom layout.
SDAPS version: 1.9.6

**Comment by sorXCode** [comment]
I got the same error using the custom.tex on the website.

\documentclass[english,pagemark,stamp]{sdapsclassic}
\usepackage[utf8]{inputenc}
\usepackage{multicol}

\author{The Author}
\title{The Title}

\begin{document}
  \begin{questionnaire}
    \begin{info}
    \end{info}
  \addinfo{Date}{10.03.2013}

    \section{Choice questions}

    For multiple choice questions we need the following metadata
    \begin{enumerate}
      \item a question text,
      \item positions of all boxes (either checkbox or textboxes), and
      \item an answer string for each of the boxes.
    \end{enumerate}
    Currently textboxes are not properly supported unfortunately (this is because
    the SDAPS class does not expose the box generation code for textboxes
    separately). To fix this the vertically/horizontally stretching textbox code
    needs to be separated out of the \textbackslash{}textbox and
    \textbackslash{}choiceitemtext commands.

    SDAPS does not care about the document itself. The only important thing is
    that it has the metadata. The position of the boxes is provided automatically
    by the \textbackslash{}checkbox command, you only need to provide the rest of
    the metadata. So the following works:


    What do you think about SDAPS?

    \immediate\write\sdapsoutfile{\unexpanded{QObject-Choice=Opinion about SDAPS}}
    \checkbox~It is very good\newline
    \checkbox~It is adequate\newline
    \checkbox~It does not work for me

    \immediate\write\sdapsoutfile{\unexpanded{Answer-Choice=good}}%
    \immediate\write\sdapsoutfile{\unexpanded{Answer-Choice=adequate}}%
    \immediate\write\sdapsoutfile{\unexpanded{Answer-Choice=bad}}%

  \end{questionnaire}
\end{document}

**Comment by benzea** [comment]
Hm, which example was that? I thin k you are using something that used to work on the old stable version of SDAPS, but it doesn't work anymore these days.

Could you have a look at https://sdaps.org/class-doc/customlayout.html and see if that works for you?

**Comment by sorXCode** [comment]
oh, okay. I just tried that, and it worked like charm! Thanks.

How can I add multiple textboxes as option choice to a question, I want to get multiple text input from the respondent. I've tried this: 
`\myquestionbegin{provide_interest}{Choice}{Interests}
\large{\textbf{{\textrm{Provide two field are you interested in: }}}}
\myanswer{Interests}
\ExplSyntaxOn
	\sdaps_textbox_hstretch:nnnnn{}{1mm}{5mm}{20mm}{1bp} \hspace{1mm}
	\sdaps_textbox_hstretch:nnnnn{}{1mm}{5mm}{20mm}{1bp}
\ExplSyntaxOff
\myquestionend{provide_interest}
`
but got this error

`Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/setup.py", line 53, in setup
    cmdline['add'])
  File "/usr/lib/python3/dist-packages/sdaps/setuptex/__init__.py", line 120, in setup
    qobject.setup.validate()
  File "/usr/lib/python3/dist-packages/sdaps/setup/buddies.py", line 114, in validate
    raise AssertionError(_("Error in question \"%s\"") % self.obj.question)
AssertionError: Error in question "Interests"`

any alternative?

**Comment by benzea** [comment]
You need an answer per box.

**Comment by sorXCode** [comment]
okay. Let me try that.

**Comment by sorXCode** [comment]
Worked!! Thanks.
