### ISSUE TITLE
Error while --add

### ISSUE THREAD

**Issue by Sahilbuddy4study** [sdaps/sdaps#174]
Hey,
I converted .jpg to .tif using Imagemagick with command:
`convert sample2.jpg -units PixelsPerInch -density 300 -threshold 50% -monochrome page_N.tif
`
then did :
`tiffcp page_*.tif joined.tif
`
and now using joined.tif in add command via :
`sdaps add sdaps/project joined.tif
`
and now i am getting this error :
`Invalid input file joined.tif. You need to specify a (multipage) monochrome TIFF as input.`
I have attached both the files .
kindly help 
Thanks
![sample2](https://user-images.githubusercontent.com/49262988/58075425-5668e700-7bc5-11e9-95ac-d8e4c39096fa.jpg)

[tif.zip](https://github.com/sdaps/sdaps/files/3201192/tif.zip)

**Comment by benzea** [comment]
As the message says, sdaps uses monochrome files internally. I would suggest that you simply import the jpegs directly by using the `--convert` option (which uses OpenCV internally so might need a further dependency).

Alternatively you need to ensure that convert converts the file to be monochrome. See https://sdaps.org/documentation/scanning/#converting-data-that-is-not-in-the-correct-format

Closing this ticket for now, feel free to reopen/ask questions here if this information is not sufficient.

**Comment by benzea** [comment]
Oh, I didn't look quite properly.

**Comment by benzea** [comment]
Tiffinfo says:

```
TIFF Directory at offset 0x849908 (8689928)
  Image Width: 2480 Image Length: 3504
  Resolution: 300, 300 pixels/inch
  Bits/Sample: 8
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 3
  Planar Configuration: single image plane
  Page Number: 0-1
  ImageDescription: 
  White Point: 0.3127-0.329
  PrimaryChromaticities: 0.640000,0.330000,0.300000,0.600000,0.150000,0.060000
```

So, looks like it is a greyscale image rather than monochrome. I remember that convert can be a bit weird in e.g. the order of arguments and such things. In this case, I suspect it decides for some reason that the file needs to be stored as a greyscale image even though it is monochrome.

I would still suggest trying `add --convert` as that is likely to give better results overall.

**Comment by Sahilbuddy4study** [comment]
Hey,
Thanks for the reply
Would surely try with
`add --convert`

**Comment by Sahilbuddy4study** [comment]
Hey,
Seems like now the Barcode is not readable.
getting this now
[tif.zip](https://github.com/sdaps/sdaps/files/3201920/tif.zip)
 
`Warning: Got a wrong survey ID (1.tif, 0)! It is 32498923, but should be 4016132417.`
I have attached the .tif file that i got after this:
`sdaps add sdaps/project --convert sample2.jpg`

Thanks

**Comment by benzea** [comment]
The barcode *is* readable. You printed the draft and the barcode there is just a dummy. You need to print the questionnaire that is generated in the project folder (without the "draft" overlay).

**Comment by Sahilbuddy4study** [comment]
Ohhh, 
Thanks for the assistance.

**Comment by Sahilbuddy4study** [comment]
Hey,
Thanks again for the help.
I successfully created the report with all data .
I want to get the textbox filled data into csv.
Is it possible to get manually filed textboxes in csv ?
@benzea

**Comment by benzea** [comment]
Only as images or if you type them off in the UI manually. SDAPS currently does not support any text recognition at all.

**Comment by Sahilbuddy4study** [comment]
Ohhk,
Thanks for the help !
