### ISSUE TITLE
stamp

### ISSUE THREAD

**Issue by fintoo** [sdaps/sdaps#180]
Hi
There's been similar issues before but I didn't get an answer to our problem. In our survey the last section - because it needs to follow a specific structure including a table - is using normal non-sdaps commands.
In sdaps, when I use setup, everything works fine and it creates the same pdf as initially in latex. However, when I want to create unique ID-surveys, sdaps just keeps running. It doesn't compile the surveys but it also doesnt give an error message. If I get rid of this last section, everything works fine.

I'm new to sdaps and ubuntu and not tech savvy at all.

The latex file for that specific section (start of it) looks as follows:

\LetLtxMacro\itemold\item
\renewcommand{\item}{\itemindent-0.25cm\itemold}

\vspace{4em}
\section{Abschnitt}

%%30 row version for q6.1 etc.
\renewcommand{\arraystretch}{1.55} %%x2 the original row height 
\begin{tabular}{|p{0.6\textwidth}|p{0.15\textwidth}|p{0.15\textwidth}|}
\hline
\tb{Einflussreiche Organisationen} & \tb{Energiepolitik} \newline \tb{im Allgemeinen} & \tb{ES2050} \newline \tb{im Speziellen}\\
&\multicolumn{1}{c}{\checkmark}&\multicolumn{1}{|c|}{\checkmark}\\
\hline
\end{tabular}

**Comment by benzea** [comment]
Are you able to switch to the current unstable version? That should fix it.

Basically, you have some "fragile" content, and the old class cannot handle it. What you can do as a workaround is to put the section into e.g. a \def in the header of the file and then use that instead.

**Comment by fintoo** [comment]
Thanks for your immediate response. I wasn't able to switch to the unstable version yet (it department authorization required). 

We are using the sdapsclassic class in latex. Is this what you are referring to with "old class" or the actual version of sdaps? 

Regarding the \def workaround: is this what you mean?
header of the file: 
 \def\SectionX{EntireContentFromSectionX}

where we want section X: 
 \SectionX

**Comment by benzea** [comment]
> We are using the sdapsclassic class in latex. Is this what you are referring to with "old class" or the actual version of sdaps?

Hmm, `sdapsclassic` is actually the new class. That is … odd, because there is quite a bit of care taken that this should work correctly in all cases.

Which version of SDAPS are you using, also, could you provide a document that reproduces the issue for you? That would make it easier for me to look into it.

**Comment by benzea** [comment]
And yes, the workaround should look like that.

Maybe as an explanation. When "stamping" the document is rendered multiple times. That creates some potential issues (one being `fragile` content needs careful handling, the other is that if you modify global variables that may leak between runs).

**Comment by fintoo** [comment]
Thanks! Attached a word file with the content from the latex file. 
We are using the current stable sdaps version on Ubuntu.

[TexFileCopy.docx](https://github.com/sdaps/sdaps/files/3416686/TexFileCopy.docx)

**Comment by benzea** [comment]
@fintoo please attach it as a `.txt` file instead. Even if I could open it with LibreOffice, I don't want to.

**Comment by fintoo** [comment]
sure, hope this works
[00_DE.txt](https://github.com/sdaps/sdaps/files/3416887/00_DE.txt)

**Comment by benzea** [comment]
```
\LetLtxMacro\itemold\item
\renewcommand{\item}{\itemindent-0.25cm\itemold}
```

You cannot do that. The code is run multiple times, meaning that in the second run `\itemold` becomes `\item` referencing itself. What probably works is resetting it again afterwards with `\LetLtxMacro\item\itemold`.

**Comment by fintoo** [comment]
Perfect, thank you so much!
