### ISSUE TITLE
Cannot install 1.9.7 under Debian 10

### ISSUE THREAD

**Issue by ysalmon** [sdaps/sdaps#183]
Hello,
I am trying to install sdaps 1.9.7 from the .deb file. Using the PPA with xenial gives 1.2 and installation with the bionic version fails because you require python < 3.7 and Debian 10 has python 3.7.3.

Why is there an upper limit on the python version ?

Also, it seems there is an intended 1.9.7 .deb for xenial but it failed to build on the PPA.

**Comment by benzea** [comment]
IIRC, I tried, but ubuntu xenial cannot be supported at this point anymore. Probably Texlive was too old, but I don't remember right now.

As for an upper limit on python, that does indeed sound a little bit odd.

**Comment by ysalmon** [comment]
imho texlive and friends should be a Recommends rather than a Requires, especially for older distros, because it is quite possible that the user installed a more recent texlive on their own.

**Comment by benzea** [comment]
I disagree, if someone bothers to install texlive separately, then they can also install SDAPS manually.

I know it is a bit more of a pain, but the distribution should provide a working set of software, not something that can be made to work by installing further software outside of the distribution …

**Comment by benzea** [comment]
Hmm, don't see any reason for the python versioning. Maybe this is an artefact of the build or so and will be fixed with a rebuild against the right distro.

**Comment by Miguel-Hermanns** [comment]
I have tried to install 1.9.8 in Debian 10 and the described problem with python 3.7.3 is still there. Any idea of how to overcome the issue?
