### ISSUE TITLE
Sdaps producing questionnaires with draft overlay

### ISSUE THREAD

**Issue by qodzero** [sdaps/sdaps#186]
First off I'd like to point out that, sdaps is not installed on my system, Im running it with the sdaps.py file and it works great ON THE COMMANDLINE, however I have a program Im working on and currently just want to generate questionnaires using sdaps so I figured I'd just call setup_tex.setup with the same parameters as those detailed in the cmdline.setup module in sdaps, this does indeed generate a questionnaire but it has a DRAFT overlay (Like the one seen when Benjamin did the sdaps presentation in 2015). 
Anyway, I took a different approach, instead of calling that function myself, I noticed the sdaps.py file actually just calls sdaps.main, so I went there and simply modified the main function a little, basically replaced cmdline = vars(cmdline), with a dict that looks like what vars(cmdline) returns so something like {'command':'setup', 'project':'proj_name', 'questionnaire.tex': 'path_to_questionnaire...}.

Anyway, needless to say, I get the same questionnaire with the same Draft overlay, could anyone assist

**Comment by benzea** [comment]
Whether draft is overlayed or not depends on whether each questionnaire gets a randomized ID (the bottom left barcode/qrcode). In that case, you need to `stamp` as the next step.

**Comment by qodzero** [comment]
I think im getting there now, So when I comment out `print_questionnaire_ids`, everything works great, when I use the stamp command on my project (`sdaps.py stamp -r 5 proj_name`) It runs successsfully but:

1. When I view the Pdf, the overlay is back
2. There is only one `questionnaire.pdf` file, any insights?

By the way, The documentation/tutorial on the sdaps website is waaaay outdated, can you fix that?If not, can you point me to a procedure I can take to go and fix some of the things there for other readers? for example In the current github version `sdaps /project/path setup_tex questionnaire.tex` wont work, its supposed to be `sdaps setup /project/path questionnaire.tex`

**Comment by benzea** [comment]
For the barcode, set `style=code128` in the LaTeX documentclass parameters.

A `stamp_X.pdf` file will be created (you can choose the output name), use that rather than `questionnaire.pdf`.

Yeah, the website is really outdated unfortunately. It is a git repository here (https://github.com/sdaps/website), and there is an issue about updating the website (https://github.com/sdaps/website/issues/14)

**Comment by qodzero** [comment]
Found it, thanks...I'll try to check the website issue
