### ISSUE TITLE
sdaps is picky about size of matrix

### ISSUE THREAD

**Issue by ysalmon** [sdaps/sdaps#187]
Sometimes forms are printed with a less than 100% scale due to printer driver configuration.

It seems that sdaps is picky about the size of the matrix, even with the --convert option.
With the first image below (images converted to png to embed them here ; were in tiff originally), I get a Matrix not recognized error.
![5-orig](https://user-images.githubusercontent.com/536850/66519440-a6e6cf80-eae7-11e9-9ccd-ce61c9edd965.png)

When I cut out the white border, sdaps finds it fine. (Github makes the image appear bigger to fit the width of the container ; actually the text and matrix are the same size in both images)
![5-recadre](https://user-images.githubusercontent.com/536850/66519439-a6e6cf80-eae7-11e9-9b04-ec1e9e23ad97.png)

Is there some parameter that I can tweak to make sdaps try to sort of zoom in when its first try at finding the matrix does not work ?

**Comment by benzea** [comment]
Yeah, it is …

The corner mark algorithm is pretty sucky. That said, you can try increasing `corner_mark_search_distance` in defs.py.

**Comment by benzea** [comment]
But seriously, the margins you have there are rather extreme …

**Comment by ysalmon** [comment]
I agree, I think the colleague responsible for printing misconfigured the things and I will try to see how to avoid this in the future, but I also do not want to reprint everything. I will have a look into defs.py.

**Comment by benzea** [comment]
If you can crop in-bulk, then that might be the best option.

**Comment by benzea** [comment]
Closing, nothing to do really ... other than replacing the algorithm possibly (which I am not planning on working on myself at least).
