### ISSUE TITLE
foreign key definition in sqlite DB is illegal

### ISSUE THREAD

**Issue by ysalmon** [sdaps/sdaps#189]
When trying to add or remove rows in the sheets table of an sdaps project's sqlite file, I got foreign key errors when ``pragma foreign_keys = true;`` is set.

Turns out it is not legal to use the rowid as a foreign key, as is [currently done](https://github.com/sdaps/sdaps/blob/fd7bf833e09328e6976a44bf59c4cd5261f4e1f1/sdaps/model/survey.py#L50).

[A solution](https://github.com/pawelsalawa/sqlitestudio/issues/3596#issuecomment-544124725) is to create an auto-incremented column.

**Comment by benzea** [comment]
Right, sounds simple enough. We probably need some migration code though to update existing projects.
