### ISSUE TITLE
Compiling tex file with pdflatex using latest unstable release

### ISSUE THREAD

**Issue by abers** [sdaps/sdaps#198]
Apologies, I am relatively new to LaTeX so assuming I am doing something wrong. Running "sdaps /tmp/project example.tex" works fine. However, I am trying to compile the example.tex file using pdflatex with the latest unstable release of SDAPS. The documentation of the last stable release said this was possible by copying the contents of the tex folder to the same folder as the .tex file. 

So, I have the example.tex file in a folder and tried in turn copying the tex folder, the contents of the tex folder, and the contents of the class folder into the same directory. Each time running "pdflatex example.tex" I receive "LaTeX Error: File 'sdapsclassic.cls' not found".

**Comment by benzea** [comment]
You need to use the example from the sources. There is a version mismatch on the website, it is pending to be resolved but things are moving slowly …

**Comment by abers** [comment]
I was using the version from the [sources](https://github.com/sdaps/sdaps/blob/master/examples/example.tex).

**Comment by benzea** [comment]
Uh, what did you copy?

In that case it seems you copied `tex/class/*` from the checkout. However, that is the source code rather than the LaTeX files you need. Look in `build/share/sdaps/tex` and `tex/class/build/unpacked` when trying to do this from a git checkout.

**Comment by benzea** [comment]
Sorry, yeah, I read it the wrong way …

**Comment by abers** [comment]
Where are these files found when installing the latest unstable from the Ubuntu repository?

**Comment by benzea** [comment]
Could well be that they are not installed :)

That might be something to change though.
