### ISSUE TITLE
export all questionnaires with recognized green boxes as in the GUI

### ISSUE THREAD

**Issue by guillermoaguilar** [sdaps/sdaps#205]
It would be great that one could render the TIFF images with the recognition marks on top of them, very much like in the GUI. 
In this way after all questionnaires are verified, we could 'export' the corrected questionnaires for later check. (my case is with an exam, and students will like to see how their exam was corrected).
Any hints in how to do this? Thanks!!

**Comment by benzea** [comment]
Have a look at `sdaps-overlay.py` in the `custom-scripts` folder. It might not be functional currently due to the move to sqlite as a storage format though.

**Comment by guillermoaguilar** [comment]
Thanks! I'm using the version in debian package, and that is sdaps 1.2.1  .
So trying with the code on this repository, it didnt work (complained that DB didnt exist).

BUT I went back to the release 1.2.1 here in github and downloaded that code, the script `sdaps-overlay.py` works flawlessly. 

Next exam I'll do it with the latest sdaps version.

**Comment by benzea** [comment]
Well, sounds like it all works well out of the box already :)
