### ISSUE TITLE
Error with questionnaire ID recognition 

### ISSUE THREAD

**Issue by chrisbio** [sdaps/sdaps#207]
I add two .tiff files with --convert because otherwise I get this error (Invalid input file Scan.tif. You need to specify a (multipage) monochrome TIFF as input.)

The files are added successfully with --convert.

But, when I use recognize, the first file works fine but the second file does not and output this error.

In the GUI, the second file has the ''empty'' ticked for Global properties of Questionnaire ID.

------------------------------------------------------------------------------
- SDAPS -- recognize
------------------------------------------------------------------------------
2 sheets
Warning: Neither 2.tif, 0 or DUMMY, -1 has a known rotation!                    
Warning: Neither 2.tif, 0 or DUMMY, -1 has a known page number!
Warning: No page number for page 2.tif, 0 exists.
Warning: Got a wrong survey ID (2.tif, 0)! It is None, but should be 68670891.
|################################################################| 100% 00:00:00
Processed 1 of 2 sheets, took 0.135763 seconds 

Anyone know what's going on ?

Thanks a lot

**Comment by benzea** [comment]
It means that the barcode/QR-code could not be scanned. it might be a low quality scan or maybe something stupid like dirt on the scanner itself.

**Comment by benzea** [comment]
Closing. If you still have trouble, feel free to reach out again.
