### ISSUE TITLE
Rename "csv" command to "import csv" and "export csv"

### ISSUE THREAD

**Issue by TheRadialActive** [sdaps/sdaps#210]
Because the usage of the `csv` command with `import` and `export` seems a little bit odd, we might just set both subcommands as main commands.

**Comment by benzea** [comment]
Hmm, if we want to support other formats, then we may get a large set of commands. Do you think that is sane?

Right now they would be grouped by format (as seen e.g. in `sdaps --help`). We could maybe also group them by `import`/`export` though that would likely mean just swapping the order from `csv export` to `export csv` as different formats will need a different set of arguments.

Thoughts?

**Comment by benzea** [comment]
Later commits also change the `setup` and `report` commands to the same scheme for consistency.
