### ISSUE TITLE
Sdaps Recognition Review Steps

### ISSUE THREAD

**Issue by qodzero** [sdaps/sdaps#216]
Hi there, How can I programmatically review a questionnaire. As in, say in a range question with five options, sdaps recognizes the 3rd option as checked when in reality, its the fourth. I want to manually tell sdaps that its the fourth and allow it to rerecognize WITH THE CORRECTED DATA. I found the `gui` command but that spawns a Gtk window and I'd like that to not be the case. So I was wondering if you could tell me how you implemented that gui logic because I looked at the code and didnt understand a thing, sorry Gtk is not in my skillset. A simple script example will be sufficient. Thanks for the great project

**Comment by benzea** [comment]
I am not sure what you want from me.

Sure, the GUI logic is non-trivial, but I don't know how I could create a simpler example for it.

It sounds like you want to do manual corrections. That does require showing the image, allowing input and updating the underlying database. Similar code is also in https://github.com/sdaps/sdaps_web and maybe the `custom-scripts` might help in making some of it understandable.

**Comment by benzea** [comment]
Closing, still not sure how I can help here …
