### ISSUE TITLE
Error on sdaps setup

### ISSUE THREAD

**Issue by EvgeniyZo** [sdaps/sdaps#217]
Last version of sdaps used

sdaps setup causes an error when image included in tex file
image included like this:
`\usepackage{graphicx}\graphicspath{{images/}}`
`\raisebox{-0.0cm}{\includegraphics[width=2cm]{image.png}}`

There is no possibility to copy images into directory before running setup because of this:
`Error: The survey directory already exists.`

But if image copied into project directory after start and before end of execution of 'sdaps setup' it works good

Maybe worth adding something like
`sdaps setup projectname doc.tex --direxists`

**Comment by benzea** [comment]
There is, you can use `--add` and the path will be copied.

See https://sdaps.org/class-doc/FAQ.html

**Comment by benzea** [comment]
Oh … I need to update the example to the new command line syntax.
