### ISSUE TITLE
Improve CSV export

### ISSUE THREAD

**Issue by benzea** [sdaps/sdaps#221]
I got feedback from some people using R.

They say, for single choice items, we should export an empty field if there is no answer. And `-1` it is invalid (i.e. multiple selections):

**Comment by benzea** [comment]
Actually, let's do empty string and `error` as that leaves integers that may be user chosen intact.

**Comment by TheRadialActive** [comment]
Empty string is fine with me, but  I am not sure about "error" as a string: If you import a csv file into R(Studio), and you have strings and integers mixed up, you may have to convert them, which isn't that convenient.

**Comment by benzea** [comment]
Hmm, I was told that a string would be fine (in R studio). I'll ask those guys again what they think.

**Comment by sjewo** [comment]
@TheRadialActive pointed this issue out to me. I checked different R functions for importing csv files and by default all of them interpret the string "NA" as missing values.

If I may add a suggestion: An error code (not recognized, multiple selections...) might be more informative for the user.

**Comment by benzea** [comment]
> If I may add a suggestion: An error code (not recognized, multiple selections...) might be more informative for the user.

There are only two cases:
 1. No checkbox has been marked
 2. Multiple checkboxes have been marked

The first case can be considered valid. The second case is an error as we cannot report a proper value.

**Comment by benzea** [comment]
OK, how about:
 * `"NA"`
 * `"error-multi-select"`
