### ISSUE TITLE
broken links in getting started tutorial

### ISSUE THREAD

**Issue by Londane** [sdaps/sdaps#224]
the follwing links get a 404;
* https://sdaps.org/files/example-scan.pdf
* https://sdaps.org/files/project_example.zip

they are on: 
* **Printing and Scanning** https://sdaps.org/getting-started/print-scan/ 
* **Adding Scans to a Project** https://sdaps.org/getting-started/add/

**Comment by benzea** [comment]
Heh, seems like I forgot to add the files. Fixed now.
