### ISSUE TITLE
Issue setting up project example

### ISSUE THREAD

**Issue by leves026** [sdaps/sdaps#225]
Hello!

I've been working through the tutorial and have been running into a problem while setting up the survey directory. Like other threads (Issue #218 / #206 / #196), I get a similar error message after running the setup command:

> sdaps setup tex /documents/sdaps-project questionnaire.tex
> \------------------------------------------------------------------------------
> \- SDAPS -- setup
> \------------------------------------------------------------------------------
> Error: The survey directory already exists.

However, unlike other examples I've seen, I get no tracebacks. Therefore I'm lost on how to diagnose the issue. Any subsequent commands (add, recognize, etc.) all say that the DB file does not exist.

Other threads say to check the log file, which I can get after running pdflatex in a separate command. No missing packages or errors there. I'm also able to go through the rest of the tutorial using the [prepared example project](https://sdaps.org/getting-started/add/). The issue for me really falls under the setup command, and would like to know if Benjamin @benzea or someone else has a suggestion on what to do!

I am using SDAPS version 1.9.9 on Ubuntu 18.04 bionic, and the .tex file is up-to-date in terms of document class (sdapsclassic) and the choicequestion code (per #127).

**Comment by leves026** [comment]
Figured it out. I was using the current directory path as the project, when instead I should have created a new folder within the directory using the setup command:

> ~/documents/sdaps-project$ sdaps setup tex [new folder name] questionnaire.tex

**Comment by benzea** [comment]
Yeah, I was going to write an explanation but didn't get around to that.

@leves026 if you have an idea on how to improve the errors or tutorial to make it clearer I would appreciate that. i.e. that a new directory will be created and that the content of this directory is managed by SDAPS.
