### ISSUE TITLE
Update from obsolete scrpage2 to scrlayer-scrpage

### ISSUE THREAD

**Issue by palmaway** [sdaps/sdaps#226]
Hi,

Trying to compile and check version 1.9.9 fails on my machine due to a LaTeX error:
`! LaTeX Error: File 'scrpage2.sty' not found.`

This is due to the presence of `\usepackage{scrpage2}` in at least 3 files:
```
tex/class/testfiles/base.lvt
tex/sdapsreport.cls
test/projects/test-tex-ids/sdapsreport.cls
```

The author has declared the package scrpage2 obsolete. It is no longer included in TeX live and MikTeX. Users are advised to switch to the successor package scrlayer-scrpage. Apparently all commands and options of scrpage2 are also recognised by scrlayer-scrpage, so a switch should be easy enough.

Could you please update any TeX file from scrpage2 to scrlayer-scrpage?

Thanks!

**Comment by benzea** [comment]
I guess I also need to submit that ctan update …
