### ISSUE TITLE
Issues with headings for custom layouts

### ISSUE THREAD

**Issue by stimon** [sdaps/sdaps#229]
I am having problems to generate headings for my custom layouts. I used to call `\question{header text}`, which now fails if it is outside of the proper context, I guess. The [documentation entry for headings](https://sdaps.org/class-doc/customlayout.html#headings) is not very clear, so I'm not sure how to proceed. 

Thanks!

**Comment by benzea** [comment]
Do you mean all the commented out `\question{}` commands in your document? e.g.:

```
    %\question{Antall års utdanning fra og med skolestart}
Antall års utdanning fra og med skolestart
    \writtendigits{edu_years_text}{2}\\
    \begin{choicegroup}[colsep=2pt,singlechoice, noalign,  var=edu_years]{}
```

That seems like a tough one. Because LaTeX doesn't like placing the "writtendigits" question into a subsection.

I suppose, something like the following can work:

```
    \newsavebox\tmpbox
    \savebox\tmpbox{\writtendigits{edu_years_text}{2}}
    \subsection{Antall års utdanning fra og med skolestart \usebox\tmpbox}
    \begin{choicegroup}[colsep=2pt,singlechoice, noalign, var=edu_years]{}
```
or
```
    \newsavebox\tmpbox
    \savebox\tmpbox{\writtendigits{edu_years_text}{2}}
    \begin{choicegroup}[colsep=2pt,singlechoice, noalign, text={Antall års utdanning fra og med skolestart}, var=edu_years]{Antall års utdanning fra og med skolestart \usebox\tmpbox}
```

Where the question is repeated in "text" so that the \usebox\tmpbox does not show up in the metadata. You might not care though, unless you want to try to use the integrated LaTeX based report.

**Comment by benzea** [comment]
NOTE: Never *ever* place such a saved box twice!

NOTE2: You obviously only need to do the `\newsavebox` once.

**Comment by stimon** [comment]
Thanks @benzea! This seems to work. 
After inspecting sdapsclassic, I figured to use `_sdaps_classic_question` to render numbered headings. I barely understand what is going on there, so maybe it is not the right solution :D
```latex
\let\qhead\_sdaps_classic_question

\qhead{Antall års utdanning fra og med skolestart}
\writtendigits{edu_years_text}{2}\\
\begin{choicegroup}[colsep=2pt,singlechoice, noalign,  var=edu_years]{}
.
.
.
```
I will change it to use your solution.

**Comment by benzea** [comment]
Probably works, but no guarantees that it randomly breaks! :)

For some of the stuff you are doing, we should probably figure out if we can add nice first-level support into the class itself.
