### ISSUE TITLE
Code 128 not found

### ISSUE THREAD

**Issue by juliafich** [sdaps/sdaps#230]
I was trying to run my first project and encountered the same issue as #32, where sdaps gave me the error notificiation "the home directory already exists". 
So I had a look at the latex file, and it runs into the error "code 128 not found". I tried running the sectsty.ins file to produce the package file sectsty.sty, which doesn't work either.

I have been trying to get this to work for over 2 weeks now, but since I have no experience working with Linux at all, this is all quite complicated for me. Hopefully someone can help.

**Comment by benzea** [comment]
There is probably another issue. Please have a close look at the (error) log (there is a .log file), going up from the end until you find the first error.

**Comment by benzea** [comment]
You could have also attached the .log file here. Anyway, too old, nothing actionable for me at this point unfortunately.

But, feel free to reach out again.
