### ISSUE TITLE
Longing for help in running sdaps

### ISSUE THREAD

**Issue by michaeljosef** [sdaps/sdaps#231]
Hello there,

I installed Ubuntu 20.04 Focal to use sdaps.
I installed texlive-full via apt-get
I installed all the mentioned packages and further on in the readme
I installed sdaps via apt-get (i know it is not the latest version but i thought it fits more the architectureprobably)

So if I try now the example routine to see if everything works i experience the following issues:
1) Try rendering the pdf via _pdflatex example.tex_, that works fine
2) _sdaps setup tex /tmp/project example.tex_, it does generate the command without error but the output is without recognizing the content of the questionnaire and looks like this
_This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
The Title
Author: The Author
Date: 10.03.2013
(base) michael@michael-consentiv:~/project_draft$_ 
3) trying to convert the pdf to tiff using the prestructured scan i get this error
_(base) michael@michael-consentiv:~/project_draft/example2$ sdaps add ./project_draft/example2 --convert example-scan.pdf
------------------------------------------------------------------------------
- SDAPS -- add
------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/script.py", line 119, in decorated_function
    log.logfile.open(os.path.join(cmdline['project'], 'log'))
  File "/usr/lib/python3/dist-packages/sdaps/log.py", line 134, in open
    logfile = Encoder(open(filename, 'a'))
FileNotFoundError: [Errno 2] No such file or directory: './project_draft/example2/log'_

**I really want this to work and would appreciate some help, if possible also in a call via telegram etc. or maybe you know already what to answear to help me solve my issues. I invested now about 10 hours with installing and deinstalling and trying but i am out of my knowledge.**

4) When seting up using the questionnaire we designed in Latex i get the following error
_This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
Error: Caught an Exception while parsing the SDAPS file. The current state is:
Questionnaire

------------------------------------
Error: An error occured in the setup routine. The survey directory still exists. You can for example check the questionnaire.log file for LaTeX compile errors.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sdaps/__init__.py", line 65, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python3/dist-packages/sdaps/cmdline/setup.py", line 49, in setup
    return setuptex.setup(cmdline['project'],
  File "/usr/lib/python3/dist-packages/sdaps/setuptex/__init__.py", line 116, in setup
    sdapsfileparser.parse(survey)
  File "/usr/lib/python3/dist-packages/sdaps/setuptex/sdapsfileparser.py", line 54, in parse
    sdaps_file = open(survey.path('questionnaire.sdaps'))
FileNotFoundError: [Errno 2] No such file or directory: 'SBER2/questionnaire.sdaps'_

but i think the latest one i could solve with rewriting the latex file according to example.tex

**Every help appreciated you guys and girls. I really want this to work.**

Kind regards
Michael from Vienna-Austria

**Comment by benzea** [comment]
This is weird.

One thing to double check. Are you sure that you used the same project directory in both cases? i.e. first you do `sdaps setup tex /tmp/project example.tex` (i.e. `/tmp/project`) and then later `sdaps add ./project_draft/example2 --convert example-scan.pdf` (i.e. `./project_draf/example2`).

Also, `_(base) michael@michael-consentiv:~/project_draft/example2$ sdaps add ./project_draft/example2 --convert example-scan.pdf` doesn't make much sense, as you are already inside the directory, so the command line should probably be `sdaps add . --convert example-scan.pdf `.

**Comment by michaeljosef** [comment]
Hey there benzea

thank you for answearing my request. 

The double check is clear. It were just different tries with different folder. 
 
I tried it through again an remembered that sdaps never can create a folder. This is why i manually create the folder, go to the folder directory and try the setup command. Maybe there is the error? It narrowed allthough now a little down, as

1) pdflatex command can now only compile the own-made document SBER.tex and fails with example.tex. It gives me different errors regarding the style. With the SBER.tex the error seems to has something to do with the latex format as well, so i will first try to find a way to have a convinient document for sdaps and for pdflatex commands and tell you then the result. **Or is there another solution, like using Open-Office? I just heared it is possible but did no where find a instruction.**

2) the command line for transforming the pdf to a tiff now works, so i am a big step further. the missing part was the "." as far i can understand it. I also conceeded all further steps until the csv document. So only the "setup add" comment needs to be fixed and i am ready to go.

I keep you updated.

**Many thanks, your comment helped me to gain trust again that i can achieve the goal of using sdaps properly.**

Kind regards
Michael

**Comment by benzea** [comment]
> I tried it through again an remembered that sdaps never can create a folder. 

Hm, that one is weird. sdaps will create the folder when running `setup tex`, it will only create one level of the hierarchy though.

> Or is there another solution, like using Open-Office? I just heared it is possible but did no where find a instruction

There was one for Open-Office. However, it was really hard to use and kept breaking in regular intervals.

> the command line for transforming the pdf to a tiff now works …

But, were you using `sdaps convert` there or are you using `sdaps add --convert`. The second should already add the document, so the only thing missing could be running `sdaps recognize .` afterwards.

**Comment by michaeljosef** [comment]
I will try to create a one-level hierachy, maybe i missed this and always tried two level

I was usin "sdaps add . --convert example-scan.pdf" as you mentioned in your previous post. Do i understand it correct, that with this command I am ready to run the whole process? If so I will try to fill out some dummy sheets right away and see tonight on my ubuntu-machine if it works through.

**Comment by benzea** [comment]
> Do i understand it correct, that with this command I am ready to run the whole process?

It just "adds" the images. It does not run the recognition process. You need to trigger each required step separately in the correct order (i.e. `setup`, `add`, `recognize`, `export`, and re-running `recognize` if you `add` more data)

**Comment by michaeljosef** [comment]
Hey Benzea,

after letting the project rest for some weeks due to other issues in professional field, I am glad to announce that I got it working and in the Beta-Test it recognized 100% correct. For the Comments I though still need to review the sheets :) 

I am willing as well to donate my time for you guys for future tests or to write an installation guide or something or a document called "my way to using sdaps, from installing linux to getting the csv-report" or something like this. Let me know about that. I am not coding though. You can reach out to me for something like that. 

Thanks for your support and help
Michael

**Comment by jfrost2420** [comment]
Hello Michael,
I too am trying to get sdaps working.  I have installed it on Ubuntu and can run _pdflatex example.tex_ . However I am not having success creating the sdaps project.  CVould you share your notes you used to get it working?

Thanks so much!
John

**Comment by michaeljosef** [comment]
Hey there John

enclosed you find my step-by-step instruction, although written in german
but the code should say it for itself

Kind regards
Michael

Am So., 6. Feb. 2022 um 20:53 Uhr schrieb John Frost <
***@***.***>:

**Comment by benzea** [comment]
> enclosed you find my step-by-step instruction

I fear that didn't work. github must have simply ignored the attachment.

**Comment by jfrost2420** [comment]
Hello again Michael - as @benzea mentioned looks like the attachment was not accepted.  I did have more success running:
sdaps setup tex test3.tex
This created a tex folder containing questionaire.pdf (this is good :) )
However, the output from running the sdaps command above shows the following:

```
john@john-VirtualBox:~/test3$ sdaps setup tex test3.tex
------------------------------------------------------------------------------
- SDAPS -- setup
------------------------------------------------------------------------------
Running pdflatex now multiple times to generate the questionnaire.
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
Running pdflatex now multiple imes to generate the questionnaire.
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
The Title
Author: The Author
john@john-VirtualBox:~/test3$
```
This appears correct - however looking at the sdaps getting started documentation the output does not show anything related to the questionnaire - for example:

```
Questionnaire
1(Head) Range Questions
1.1(Mark) How often do you use SDAPS? {1}
        never - daily
        0(Checkbox)  87.8  78.4   3.5   3.5
[SNIP] 
```

Is this correct?  Or maybe I am missing something.

I am attaching the test3.tex (renamed to .txt to allow for upload) and the generated questionnaire.pdf.

Thanks so much for any assistance!
[questionnaire (1).pdf](https://github.com/sdaps/sdaps/files/8053941/questionnaire.1.pdf)
[test3.txt](https://github.com/sdaps/sdaps/files/8053953/test3.txt)

**Comment by jfrost2420** [comment]
thank you @benzea .  I am making progress.  I believe I ran the sdaps add and sdaps recognize steps successfully.  However when I create the report or run the gui, it appears as if nothing was recognized.  Here is the output for sdaps add and sdaps recognize:
```
john@john-VirtualBox:~/test3/tex$ sdaps add . --convert /home/john/test3/question2.pdf
------------------------------------------------------------------------------
- SDAPS -- add
------------------------------------------------------------------------------
Converting input files into a single temporary file.
/home/john/test3/question2.pdf: Not a TIFF or MDI file, bad magic number 20517 (0x5025).
Processing /tmp/sdaps-convert-u_1sx3k1.tif
Done
john@john-VirtualBox:~/test3/tex$ sdaps recognize .
------------------------------------------------------------------------------
- SDAPS -- recognize
------------------------------------------------------------------------------
4 sheets
Warning: Neither 1.tif, 0 or DUMMY, -1 has a known rotation!                    
Warning: Neither 1.tif, 0 or DUMMY, -1 has a known page number!
Warning: No page number for page 1.tif, 0 exists.
Warning: Got a wrong survey ID (1.tif, 0)! It is None, but should be 3302320947.
|################################################################| 100% 00:00:00
Processed 1 of 4 sheets, took 0.585104 seconds 
```
However the gui and the report does not show any completed questions.  Please see the atatched screenshot from the gui.  I feel that I am really close, must be missing something.  Thanks again for any help!

John
![Screen Shot 2022-02-12 at 6 47 44 PM](https://user-images.githubusercontent.com/1542468/153732546-0dfe6b69-6b02-46e8-8a6b-1a09a9e0471e.png)

**Comment by michaeljosef** [comment]
Hey there

Here my file as pdf https://we.tl/t-UZBJl3DIvZ as download on we-transfer

hope it helps to make it work

Kind regards
Michael

Am So., 13. Feb. 2022 um 00:52 Uhr schrieb John Frost <
***@***.***>:

**Comment by benzea** [comment]
@jfrost2420, it couldn't read the QR code in the bottom right corner. Please try different options on the scanner to get a better image.

**Comment by benzea** [comment]
I hope you managed to get things to work! If not, feel free to reach out again.
