### ISSUE TITLE
Can \choicequestion and \optionquestion groups be given a vertical layout?

### ISSUE THREAD

**Issue by cojohnson1999** [sdaps/sdaps#232]
Hi there,

I've recently created a program that generates a Latex document using SDAPS's Latex classes.  The forms turn out pretty good, but the question setup is strange in some cases.  All of the \choicequestion and \optionquestion groups organize answers horizontally, while I think they'd look better if placed vertically.  I've looked around on most all of the documentation and haven't been able to find any solutions, so any help would be much appreciated.

**Comment by benzea** [comment]
Hmm, no, the way it works right now it is not really possible. And, to be honest, I am not sure how it could work when combined with the "multicol" type items.

Not sure what look you are going for, but maybe a combination with `multicols` might work? Though, honestly, I doubt it'll give the result you are looking for (the question itself would not span the columns currently).

**Comment by cojohnson1999** [comment]
Sorry for the delayed response, benzea.  I tried a number of things with multicol and couldn't really get it working properly.  I was trying to get each question's answer choices to align themselves from
1     2
3     4
to 
1     3
2     4
with choicemulticolitems, but I couldn't find any way to do it.

However, the people at the top of the project I'm working for said they preferred only one column of choices for a question anyway, so as far as I'm concerned it isn't really much of an issue anymore.  Gonna close the thread now, but maybe it would be a good option to add in the future?

**Comment by benzea** [comment]
I think it would be worth for you to open a feature request against sdaps-class.

That would be mostly useful if you could provide a mockup of what it should look like. The interesting point here is how to handle corner cases, e.g.:
 * Should rows always be aligned?
 * Can items be multiline? If yes, what happens in the next column? Would users need to specify that it is spanning multiple rows?
 * Can items span multiple columns? That would likely be harder to implement though.
 * Should layout look similar to `choicequestion` with the checkbox at the front?
