### ISSUE TITLE
Question about changing recognition confidence levels with the recognize command

### ISSUE THREAD

**Issue by cojohnson1999** [sdaps/sdaps#234]
Is it possible to change anything in SDAPS's source files to alter the "confidence level" required to consider each marked answer on a scanned document as marked?  For example, could I change it to where SDAPS only recognizes a question as marked if it is 95% or more sure that the question is marked?  I've looked through the source files and couldn't really tell what if anything you could change to achieve this.  Any help would be much appreciated!

**Comment by benzea** [comment]
There is no such thing as 95% confidence (and, in my experience it is higher).

You can do two things:

1. Change the mode. i.e. disabling the correction feature (by filling) and switching to either check or fill for marking.
2. You can change `defs.py` to change things a bit. Basically, it is a mapping from filling various heuristics to a "quality" value and then the best one is chosen. This "quality" is **not** a confidence at all, it is just meant to be a monotonic mapping that represents how good the match is.

**Comment by cojohnson1999** [comment]
Awesome, that's exactly what I was looking for.  I was curious to see if there was any way to tweak the recognition a little bit and that does it perfectly.  Thanks benzea!

**Comment by benzea** [comment]
btw. if you actually want to adjust the numbers, then use the `boxgallery` command. It'll give you detailed debug information about every checkbox there is.
