### ISSUE TITLE
Can stamped QR Code IDs be added as a number to each stamped document?

### ISSUE THREAD

**Issue by cojohnson1999** [sdaps/sdaps#235]
Hi there, the institution I'm working with using SDAPS was curious if there was any way that individually-stamped questionnaire IDs could be added somewhere on each document as a numerical value, similar to a page number but only distinguishing between printed questionnaires.  They were hoping there was some way to number each document so that each individual one can be told apart and sent to the right person, since using QR code readers to differentiate them would be a lot of work for the questionnaire distributors.

I haven't been able to find any way to do this so far, but I thought it was worth asking.  Thanks!

**Comment by benzea** [comment]
Heh, maybe it isn't documented anywhere?

This is possible. You do however need to be extremely careful that this does not cause any changes in the document layout. I would suggest at least using `\strut` and plenty of space in the line, or some other mechanism like a minipage with a fixed size.

Anyway, just use `\qid` to get the ID. I suppose you could load more information from a separate file, look up the qid (or open the file based on the qid) and e.g. render a full address field for a letter that way.

**Comment by cojohnson1999** [comment]
Amazing, that's exactly what I was looking for.  I ended up putting the qid in the title of the LaTeX questionnaire, and it looks and works great as an identifier in the stamped printouts.  I appreciate the help!!!
