### ISSUE TITLE
Version 1.9.10 on sdaps-class and 1.9.9 on sdaps

### ISSUE THREAD

**Issue by vincentxavier** [sdaps/sdaps#238]
There's a version mismatch between the LaTeX class and the package.
This renders sdaps unusable on Debian.

**Comment by vincentxavier** [comment]
It seems as sdaps-class submodule haven't been update.

**Comment by benzea** [comment]
Hmm, it is true that the version mismatch exists (I did a new class tarball but didn't release a new SDAPS version).

I am a bit confused why this creates a problem though. Is there a versioned dependency in the package?

**Comment by vincentxavier** [comment]
Le mardi 14 décembre 2021 10:45:58 CET Benjamin Berg a écrit :> Hmm, it is 
true that the version mismatch exists (I did a new class tarball
> but didn't release a new SDAPS version).
> 
> I am a bit confused why this creates a problem though. Is there a versioned
> dependency in the package?
No, but as you use the workflow described in the documentation  :

1. You write the document in your main LaTeX repository (it uses the CTAN 
package)
2. You setup the project, using `sdaps setup /tmp/projet/ qcm.tex` (it copies 
the `/usr/share/sdaps/tex/<files>` into /tmp/project and use this files to 
compile the project 

The compilation fails because the tex file wants some other versions.

It may appears because I've set a custom $TEXINPUTS variable. I'll try with 
this variable sets to Debian default.

-- 
Vincent-Xavier JUMEL Id: 0xBC8C2BAB14ABB3F2 https://blog.thetys-retz.net

Société Libre, Logiciel Libre http://www.april.org/adherer
Parinux, logiciel libre à Paris : http://www.parinux.org

**Comment by benzea** [comment]
That sounds like your problem is that the package uses its own version. Which is simply buggy and does not work anymore.

A quick fix is to remove the files that the package installs. i.e. just delete the files in `/usr/share/sdaps/tex/`.

**Comment by vincentxavier** [comment]
Le 2021-12-14 11:12, Benjamin Berg a écrit :
> That sounds like your problem is that the package uses its own
> version. Which is simply buggy and does not work anymore.
> 
> A quick fix is to remove the files that the package installs. i.e.
> just delete the files in /usr/share/sdaps/tex/.
> 
In this case, could you confirm that package shouldn't install this 
files ? I've open a Debian bug, requesting a version bump. I oculd give 
some advices about this.

Thanks.
-- 
Vincent-Xavier JUMEL GPG Id: 0x14ABB3F2 http://thetys-retz.net

Rejoignez les 5334 adhérents de l'April http://www.april.org/adherer
Parinux, logiciel libre à Paris : http://www.parinux.org

**Comment by benzea** [comment]
Yes. The package should add a dependency to the LaTeX class. And then stop setting `--build-tex` and `--install-tex` in `debian/rules`.

This was set earlier (in my own packages too), because TeXLive had a bug and was missing a file.

**Comment by benzea** [comment]
OK, not sure what is happening here. Either way, SDAPS should be updated to the new release (1.9.13) that I am going to push out today or maybe tomorrow.

I'll close this issue for now.
