### ISSUE TITLE
How to add custom questionnaire IDs?

### ISSUE THREAD

**Issue by przemo** [sdaps/sdaps#240]
Hi, 
I was wondering if I can add my own list of IDs to generate multiple questionnaires. I followed the instructions on the website, however the questionnaire.pdf is still with DRAFT watermark and I can’t really find any instructions how to add custom IDs.

Thank you!

**Comment by benzea** [comment]
I assume that you have setup the project directory?

In that case, you are missing the `stamp` command, which generates a `stamp_X.pdf` file. Have a look at `sdaps stamp --help`, you probably want to use the feature to read IDs from a file, i.e. `sdaps stamp PROJECT -f id_file` where the file contains one ID per line.

**Comment by przemo** [comment]
Yes, I have the project directory. I am sorry, I totally missed the help functionality for the all the commands. All works great.
Thank you for help!
