### ISSUE TITLE
Info language changes after setup

### ISSUE THREAD

**Issue by benediktclaus** [sdaps/sdaps#243]
SDAPS is a great piece of software! However, I encountered one problem: After the setup of an SDAPS project, the info language changes from German (which is displayed fine in the preview) to English (in the questionnaire of the project itself).

Does anybody have any ideas why this is happening and how to fix it?

**Comment by benzea** [comment]
How are you compiling in each case?

That should work fine. It should load the dictionary based on the language defined in babel for the document. Is it actually english, or are you seeing odd placeholder texts?

**Comment by benediktclaus** [comment]
When building the document, I use latexmk in VS Code. Then I copy the `.tex` file to a new folder and setup an SDAPS project with

`sdaps setup example_project questionnaire.tex`

The resulting questionnaire does not seem to be build with the correct dictionary. The info text is, however, proper English. Can I specify another engine in the setup command?

**Comment by benzea** [comment]
SDAPS just runs `pdflatex` by default. Yes, you can specify the engine:
```
$ sdaps setup tex --help
usage: sdaps.py setup tex [-h] [-a ADD] [-e ENGINE] project questionnaire.tex [additional_questions]

Create a new survey from a LaTeX document. You need to be using the SDAPS class. All the metadata and
options for the project can be set inside the LaTeX document.

positional arguments:
  project               The SDAPS project.
  questionnaire.tex     The LaTeX Document
  additional_questions  Additional questions that are not part of the questionnaire.

options:
  -h, --help            show this help message and exit
  -a ADD, --add ADD     Additional files that are required by the LaTeX document and need to be copied into
                        the project directory.
  -e ENGINE, --engine ENGINE
                        The engine to use to compile LaTeX documents.
```

**Comment by benzea** [comment]
But not sure how that would help you.

**Comment by benediktclaus** [comment]
I am afraid I still encounter this problem. I guess it could be an issue with using WSL2. Since this is the only issue, I will write the info myself. That seems to be the easiest way for now.

Thanks for your help!

**Comment by benzea** [comment]
> ... I guess it could be an issue with using WSL2.

Hmm, seems unlikely, but who knows.

> Since this is the only issue, I will write the info myself. ...

Yeah, fair enough. That really isn't a big deal.

**Comment by benzea** [comment]
Closing. Would be curious to know what is going on, but as-is, I have no good idea.

(Well, the best idea I do have is that you have the LaTeX class both through your tex distribution and SDAPS, and one of them is broken)
