### ISSUE TITLE
Scan pages are messed up, then csv results are messed up?

### ISSUE THREAD

**Issue by ttkrpink** [sdaps/sdaps#261]
Here is the situation: The questionnaire has 2 pages, single-sided, stamped. Suppose there are 10 students who are taking the questionnaire. The scanned results are A1, A2, B1, B2, C1, C2, etc. When the pages are scanned, the order is messed up. The order of pages in the scan is totally random. It might be C2, E1, F2, A1, B1, D2, for example. PS, I used the code128 instead of QR.

Since each page has a survey ID and a student ID, I guess sdaps will automatically match everything.
The commands I use:

1. ./sdaps.py add project-random --convert ../Survey_wide_results.pdf
2. ./sdaps.py recognize --identify project-random
3. ./sdaps.py reorder project-random
4. ./sdaps.py recognize project-random

The outputs are:

1. Add is fine. 
2. recognize --identify: shown in the first code block
3. reorder is fine without any info
4. recognize: error shown in the second code block

if I don't reorder, the recognize can go through, but the csv result is messed up.

Any way I can fix this? Or the only thing to do is: Do not mess up the scanned page order.

Thanks for your help.

```
------------------------------------------------------------------------------
- SDAPS -- recognize
------------------------------------------------------------------------------
10 sheets
Warning: Could not read survey ID of either 1.tif, 3 or 1.tif, 4!
Warning: Got a wrong survey ID (1.tif, 3)! It is None, but should be 1294823383.
Warning: Could not read survey ID of either 1.tif, 5 or 1.tif, 6!
Warning: Got a wrong survey ID (1.tif, 5)! It is None, but should be 1294823383.
Warning: Could not read survey ID of either 1.tif, 9 or 1.tif, 10!
Warning: Got a wrong survey ID (1.tif, 9)! It is None, but should be 1294823383.
Warning: Could not read survey ID of either 1.tif, 13 or 1.tif, 14!
Warning: Got a wrong survey ID (1.tif, 13)! It is None, but should be 1294823383.
Warning: Images 1.tif, 17 and 1.tif, 18 do not have consecutive page numbers!
Warning: Page number for page 1.tif, 18 already used by another image.
Warning: Got different IDs on different pages for at least one sheet! Do *NOT* try to use filters with this survey! You have to run a "reorder" step for this to work properly!
Warning: Images 1.tif, 19 and 1.tif, 20 do not have consecutive page numbers!
Warning: Page number for page 1.tif, 20 already used by another image.
Warning: Got a wrong survey ID (1.tif, 19)! It is None, but should be 1294823383.
|################################################################| 100% 00:00:01
Processed 10 of 10 sheets, took 1.874292 seconds
```

```
------------------------------------------------------------------------------
- SDAPS -- recognize
------------------------------------------------------------------------------
11 sheets
Warning: Could not read survey ID of either 1.tif, 3 or 1.tif, 4!
Warning: Got a wrong survey ID (1.tif, 3)! It is None, but should be 1294823383.
Warning: Could not read survey ID of either 1.tif, 5 or 1.tif, 6!
Warning: Got a wrong survey ID (1.tif, 5)! It is None, but should be 1294823383.
Warning: Could not read survey ID of either 1.tif, 9 or 1.tif, 10!
Warning: Got a wrong survey ID (1.tif, 9)! It is None, but should be 1294823383.
Warning: Could not read survey ID of either 1.tif, 13 or 1.tif, 14!
Warning: Got a wrong survey ID (1.tif, 13)! It is None, but should be 1294823383.
Traceback (most recent call last):
  File "/extend2/chaoyou/tmp/sdaps/sdaps/__init__.py", line 67, in main
    return cmdline['_func'](cmdline)
  File "/extend2/chaoyou/tmp/sdaps/sdaps/script.py", line 126, in decorated_function
    result = function(cmdline)
  File "/extend2/chaoyou/tmp/sdaps/sdaps/cmdline/recognize.py", line 57, in recognize
    return recognize.recognize(survey, filter)
  File "/extend2/chaoyou/tmp/sdaps/sdaps/recognize/__init__.py", line 32, in recognize
    survey.iterate_progressbar(survey.questionnaire.recognize.recognize, filter)
  File "/extend2/chaoyou/tmp/sdaps/sdaps/model/survey.py", line 448, in iterate_progressbar
    function(*args, **kwargs)
  File "/extend2/chaoyou/tmp/sdaps/sdaps/recognize/buddies.py", line 501, in recognize
    res = self.identify(clean=False)
  File "/extend2/chaoyou/tmp/sdaps/sdaps/recognize/buddies.py", line 478, in identify
    self.obj.sheet.recognize.recognize()
  File "/extend2/chaoyou/tmp/sdaps/sdaps/recognize/buddies.py", line 89, in recognize
    self.duplex_copy_image_attr(failed_pages, 'rotated', _("Neither %s, %i or %s, %i has a known rotation!"))
  File "/extend2/chaoyou/tmp/sdaps/sdaps/recognize/buddies.py", line 301, in duplex_copy_image_attr
    second = self.obj.images[i + 1]
IndexError: list index out of range
```

**Comment by benzea** [comment]
Try running `sdaps reorder PROJECT`.

**Comment by ttkrpink** [comment]
> Hmm, "list index out of range" sounds like some duplex/simplex confusion. Did you print simplex? Did you scan duplex? Maybe the reorder code cannot deal with duplex vs. simplex somehow?

print one-sided, shuffle all pages, scanned page by page.

**Comment by benzea** [comment]
Did you set the LaTeX document into `oneside` mode then?

If you can, can you provide the entire project including the LaTeX file? It would be better to see whether everything fits together rather than just looking at the scan.

**Comment by ttkrpink** [comment]
> Did you set the LaTeX document into `oneside` mode then?

how to set the latex doc one-sided mode and how to scan in simplex mode then? I did not find much document about it


Thanks

**Comment by benzea** [comment]
In the `\documentclass` at the top of the document include `oneside` in the list (it is there in the example).

Please scan duplex and pass `--duplex` to the add command (huh, why didn't I do that the other way around, assuming a simplex scan is kinda error prone).

**Comment by benzea** [comment]
Ahh, right, looking at the scan you provided it is obvious why it is not working.

SDAPS internally assume it can treat the front/back of a page in one step (automatically filling in any information from the other side when it could not be read). In the case of a simplex document and scan, it does so by inserting empty dummy pages as a second page so that the data model can make this assumption.

In SDAPS view, you have a duplex scan. However, it really is simplex and the front/back do not belong together.

----

There is a bug though really, we should already throw an error in the first `recognize --identify` step. Having different questionnaire IDs on the front and back of a page should not be permissible. Same for having page numbers that do not fit together.

**Comment by benzea** [comment]
(Note that this also makes it obvious why duplex has an advantage overall. Even if someone/something messed up the barcode/qr-code on one side, you can still properly read it as long as the one from the other side is still intact).

**Comment by ttkrpink** [comment]
Ok, what you said made sense. 

With the current scan, I think split the 1.tiff file into separate files. Use the recognize function to identify barcode, survey id and page number, then match them accordingly, and put sorted files together to new 1.tiff.

Is there a starter document I can read to contribute?

**Comment by ttkrpink** [comment]
I will stay with double-side scan.

**Comment by benzea** [comment]
Did this work out in the end?

**Comment by ttkrpink** [comment]
> Did this work out in the end?

Decide to use the two-side print and scan. Saves a tree and has less trouble.
