### ISSUE TITLE
add command failed to create temp file.

### ISSUE THREAD

**Issue by ttkrpink** [sdaps/sdaps#263]
The add --convert returns an error. The add.py failed to create the temp file. Therefore an empty image is passed to opencv.

what might cause this problem? It should not be the permission since I put the tmp dir to a+rwx.

Thanks.

![image](https://github.com/sdaps/sdaps/assets/2522889/723d447e-d73d-4740-ab82-862e65c5f909)

**Comment by benzea** [comment]
Hmm, isn't this again the issue of poppler not being usable? i.e. installing the poppler gobject-introspection bindings and making sure that python3-gobject is installed?

**Comment by ttkrpink** [comment]
You are right. I am creating docker files and figured that I missed something. 
sudo apt install -y libpoppler-glib-dev python3-gi-cairo
