### ISSUE TITLE
On Debian, the contents of /usr/share/sdaps/tex/ should go into $TEXMFDIST/tex/latex/sdaps/

### ISSUE THREAD

**Issue by stroobandt** [sdaps/sdaps#27]
On Debian-based distributions, the contents of /usr/share/sdaps/tex/ should go into `"$(kpsewhich -expand-var '$TEXMFDIST')/tex/latex/sdaps"` instead.

Below is the install script I use now to install sdaps:

``` bash
#!/bin/bash
sudo add-apt-repository "deb http://ppa.launchpad.net/benjamin-sipsolutions/sdaps-stable/ubuntu precise main"
sudo apt-get update && sudo apt-get install sdaps
DIR="$(kpsewhich -expand-var '$TEXMFDIST')/tex/latex"
sudo mkdir $DIR/sdaps
sudo cp -R /usr/share/sdaps/tex/* $DIR/sdaps
sudo texconfig rehash
```

**Comment by Natureshadow** [comment]
In the new Debian package, I have taken care of that with two patches. Look here: https://anonscm.debian.org/cgit/debian-edu/pkg-team/sdaps.git/tree/debian/patches

One patch removes the code copying the LaTeX files, the other one is #121.

The files can simply be installed in the location mentioned above - no magic in post-install needed, as adding files to that location enabled a dpkg trigger from tex-common and does the rest.

**Comment by Natureshadow** [comment]
It might generally be advisable to remove the part copying the LaTeX files and instead simply add the data dir to `TEXINPUTS`, so files are found in all cases.

**Comment by benzea** [comment]
So, the SDAPS package is now in TeX Live, so it might just be an external dependency soon.

I am not entirely sure how to deal with that yet. We should probably stop trying to copy everything into the project directory at that point. Maybe we need an option to use the internal copy rather than the external one.

**Comment by benzea** [comment]
I opened #200 about that.
