### ISSUE TITLE
Vertical page registration

### ISSUE THREAD

**Issue by belg4mit** [sdaps/sdaps#33]
Some of our survey administrators are careless when making copies, and the horizontal components of the corner registration marks get lost, causing SDAPS to to give up, consequently requiring manual data entry of hundreds of checkboxes. Would it be possible to use the position of the bar code to help align things vertically? And if necessary, possibly assume that the outside terminals of the vertical lines for horizontal registration are where the missing lines would be? (One can calculate the angle of said lines as the complement of verticalish registration lines from true vertical)

**Comment by benzea** [comment]
In case anyone stumbles across this bug, it is now possible to manually fix this by adjusting the corner marks in the GUI and do a recognition run of the current page from there.
