### ISSUE TITLE
Redo LibreOffice support using UNO

### ISSUE THREAD

**Issue by benzea** [sdaps/sdaps#47]
The current LibreOffice support is not very nice for a couple of reasons:
- it requires parsing both ODT and PDF files. Because of this:
  - prone to break if PDF export changes
  - no support for right to left languages
  - no support for multicolumn layouts
- Style based system is hard to use

The idea is to move over to use python-uno (either as a macro, or launching libreoffice externally). Using a macro would have the advantage that one might be able to extend the LibreOffice UI to simplify questionnaire creation.

**Comment by reviczky** [comment]
https://github.com/mstamy2/PyPDF2
* Support for Python 3

That should do it!

**Comment by reviczky** [comment]
https://github.com/MrLeeh/pdftools

**Comment by benzea** [comment]
Quite likely, I am going to drop support for ODT for SDAPS 2.x for a start. Don't want this to become a roadblock in the whole project, and moving to Python 3 would make sense at the same time.

**Comment by benzea** [comment]
Support has been removed now.
