### ISSUE TITLE
Move to OpenCV 3.x (requires OpenCV release)

### ISSUE THREAD

**Issue by benzea** [sdaps/sdaps#48]
OpenCV 3.x is still in a beta stage. However, OpenCV 2.x will not support python 3, so that we need to move over to OpenCV 3.x for the "convert" package.

See also http://code.opencv.org/versions/show/3.

**Comment by reviczky** [comment]
OpenCV 3.0 gold release is now out.

http://opencv.org/opencv-3-0.html

**Comment by benzea** [comment]
This has happened. No changes were required.
