### ISSUE TITLE
Reproducing example project - No module named image

### ISSUE THREAD

**Issue by leingang** [sdaps/sdaps#55]
I was able to install sdaps but cannot add files to the example project.  

Before I get into my current issue, let me start from the beginning in case this information is relevant.  I am running MacOS 10.8 (Mountain Lion) and using the macports 2.3.2 distribution.  

When building from source, I got an error:

    $ python2.7 setup.py build
    running build
    running build_py
    running build_ext
    building 'sdaps.image.image' extension
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -pipe -Os -fwrapv -DNDEBUG -g -fwrapv -O3 -    Wall -Wstrict-prototypes -I/opt/local/Library/Frameworks/Python.framework/Versions/2.5/include/pycairo -I/opt/local/include/cairo -I/opt/local/include/pixman-1 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c     sdaps/image/wrap_image.c -o build/temp.macosx-10.8-x86_64-2.7/sdaps/image/wrap_image.o
    sdaps/image/wrap_image.c:23:10: fatal error: 'pycairo.h' file not found
    #include <pycairo.h>
             ^
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1

I found three files in my system called `pycairo.h`.  One of them is in `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/pycairo/` so I added it explicitly to the include path:

    $ python2.7 setup.py install --user build_ext -n -I/opt/local/Library/Frameworks/Python.framework/Versions/2.7/include/pycairo/

After that, build and install ran successfully.  

Also, since my default python is 3.4 I had to change line 1 of `bin/sdaps` to `#!/opt/local/bin/python2.7`.

But then I went to run the example project:

    $ cd examples
    $ ../bin/sdaps mytest setup_tex example.tex
    [works]
    $ ../bin/sdaps mytest add example.tif
    ------------------------------------------------------------------------------
    - SDAPS -- add
    ------------------------------------------------------------------------------
    No module named image
    Error: It appears you have not build the C extension. Please run "./setup.py build" in the toplevel directory.

If I'm reading `sdaps/image/__init__.py` correctly, this error is triggered when `image.so` is not installed.  But my build has no such file.  Did I mess something up?

**Comment by benzea** [comment]
OK, feel free to reopen it (or anyone else). It would be really nice if this just worked, but I don't see a point in leaving the issue open as I cannot fix it …
