### ISSUE TITLE
Allow placing images/tables etc inside 'freeform' text boxes

### ISSUE THREAD

**Issue by tornadof3** [sdaps/sdaps#62]
Is it possible to place images/tables/text inside freeform text boxes that get captured along with any text the user writes?

eg a question could have a part populated table and students 'fill in the blank' or could have part of a graph for students to complete..

thanks

**Comment by benzea** [comment]
Have you seen http://sdaps.org/FAQ#Is_it_possible_to_put_content_inside_a_freeform_textbox.3F?

I think it describes exactly this, but if there is something missing, I will be happy to add some more information.

**Comment by benzea** [comment]
Yes this is a pretty bad hack. Ideally we would have better support for it, but this would require some deeper changes.

**Comment by tornadof3** [comment]
Ah. I am very sorry for not checking FAQ, that is a dumb mistake. I will give it a go when I get a moment. Thank you.

**Comment by tornadof3** [comment]
Thank you for this link, I tried it out. Just a couple of quick questions
- how to make the inserted text/tables/items inside a textbox align to the top rather than centre (I've tried several options here to no avail) and also sometimes this messes up the formatting of the text boxes, see for example question B/3 when this renders below:

\documentclass[
  % Babel language, also used to load translations
  english,
  % Use A4 paper size, you can change this to eg. letterpaper if you need
  % the letter format. The normal methods to modify the paper size should
  % be picked up by SDAPS automatically.
  a4paper, 
  % setting this might break the example scan unfortunately
  % letterpaper
  %
  % If you need it, you can add a custom barcode at the center
  globalid=UPN558393393,
  %
  % And the following adds a per sheet barcode at the bottom left
  print_questionnaire_id,
  %
  % You can choose between twoside and oneside. twoside is the default, and
  % requires the document to be printed and scanned in duplex mode.
  %oneside,
  %
  % The following options make sense so that we can get a better feel for the
  % final look.
  pagemark,
  stamp,style=qr]{sdaps}
\usepackage[utf8]{inputenc}
% For demonstration purposes
\usepackage{multicol}
\usepackage{enumerate}
\def\checkboxstyle{ellipse}
\newcommand{\testgrade}{grade}
\renewcommand\thesubsection{\testgrade/\arabic{subsection}}
\makeatletter
\newcommand{\makenodeinlasttextbox}[1]{%
  \begin{tikzpicture}[remember picture, overlay]%
    \setlength\textheight{\@sdaps@height}
    \advance\textheight by -2pt
    \node[outer sep=1pt, inner sep=0pt, align=center, text width=\@sdaps@width-2pt, minimum height=\textheight, shift={($(\@sdaps@x,\@sdaps@y) + 0.5*(\@sdaps@width, -\@sdaps@height)$)}, anchor=center] at (current page.south west) {%
      #1%
    };
  \end{tikzpicture}
}
\makeatother
\author{\textbf{School Examinations}}
\title{Grade B Test 5}

\begin{document}
  % Everything you do should be done inside the questionnaire environment.

  % If you don't like the default text at the beginning of each questionnaire
  % you can remove it with the optional [noinfo] parameter for the environment 
  \begin{questionnaire}

	\renewcommand\testgrade{B}

\begin{multicols}{2}

    % This is a textbox which is at least 2cm high. It will automatically scale
    % to fill the page.
    \textbox{5cm}{Could you answer a question in this box?}
    
    \textbox{4cm}{Evaluate: $\displaystyle \int_{0}^{\pi}{4\sin{2\theta}d\theta}$}

	\textbox{3cm}{Find $\frac{dy}{dx}$, given that $y=2e^{3x} + 5x^2$}
    % Force a new page here
    %\newpage
  
	\textbox{15cm}{Solve the integrals:}
	\makenodeinlasttextbox{
	\begin{enumerate}[a).]\item $\displaystyle I=\int{3x^2 dx}$
	\item $\displaystyle \int{5\tan{2x}dx}$\end{enumerate}
	}  

	\textbox{15cm}{Complete the table for $y=2x^2 + 3x -1$}
	\makenodeinlasttextbox{
	\begin{tabular}{ l c r }
  1 & 2 & 3 \\
  4 & 5 & 6 \\
  7 & 8 & 9 \\
\end{tabular}
	} 
  
  
\end{multicols}
 \end{questionnaire}
\end{document}

**Comment by benzea** [comment]
So, the messed up layout is likely some issue in combination with multicol. I thought I had those fixed, but appears this is not entirely the case :-(

For the orientation something like
```
\makenodeinlasttextbox{
\parbox[t][\textheight][t]{\textwidth}{
\begin{tabular}{ l c r }
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{tabular}
}}
```
could do the trick.

**Comment by benzea** [comment]
I am at a loss about the layouting issue there. Apparently using the \raggedcolumns option helps, but it is not layed out properly either then. I don't think I will figure this one out myself.

**Comment by tornadof3** [comment]
Thanks for the suggestion re parbox; it worked well. 
As for the layout, it is strange as you say. Using \twocolumn seems better, but it leaves a blank first page!

**Comment by tornadof3** [comment]
Also, I just git-cloned the master branch (was previously using ppa .deb source - uninstalled) and tried to run setup.py install and got this:

    user@user-VirtualBox:~/sdaps/sdaps$ ./setup.py install
    running install
    running build
    running build_py
    running build_ext
    running build_scripts
    running build_i18n
    intltool-update -p -g sdaps
    ERROR: xgettext failed to generate PO tempalte file because the following     
       file contains strings marked for translation, not encoded in UTF-8.    
       Please ensure all strings marked for translation are UTF-8 encoded.  

           ./../sdaps/report/answers.py:332

    error: command 'intltool-update' failed with exit status 1

am I doing something wrong?

**Comment by benzea** [comment]
Hrm, and I just replaced that character with the UTF-8 version recently to fix another issue. Seems like we'll need some trick to use that character without confusing intltool (must be a bug in intltool).

You can replace the bullet character in line 332 with something else (e.g. *). I'll have a closer look tomorrow how I can get everything working.

**Comment by benzea** [comment]
Fixed in 154bcdad8277e0. So it was some fallout from issue #61, would have never expected something weird like this to happen. Will need to open an intltool bug about this.

**Comment by benzea** [comment]
About the two column layout. Sure, you can use \twocolumn, but then you cannot have the information text at the top over both columns.

Use ```\begin{questionnaire}[noinfo]``` (i.e. add the ```[noinfo]``` option) to prevent the information from showing up (if you need some similar information teyt, you'll need write something yourself).

**Comment by benzea** [comment]
Hehe, ok, now the proper fix for the encoding issue in commit 0d875c8d80.

**Comment by benzea** [comment]
For the record, this is/will be possible in the new class that is being developed. Some more information over at http://article.gmane.org/gmane.comp.statistics.sdaps/203.

**Comment by benzea** [comment]
I believe that this is fixed in the new class. Please open new issues for outstanding bugs.
