### ISSUE TITLE
run-test.sh fails at stamping projects/test-tex-ids

### ISSUE THREAD

**Issue by FloRinke** [sdaps/sdaps#63]
with version 1.1.9, running the test fails at stamping in project test-tex-ids. 
This is the relevant step:
```ShellSession
flo@ridcully:~/sdaps/sdaps-1.1.9/test $ sdaps projects/test-tex-ids stamp -f data/tex/code128_test_ids
------------------------------------------------------------------------------
- SDAPS -- stamp
------------------------------------------------------------------------------
Running pdflatex now twice to generate the stamped questionnaire.
This is pdfTeX, Version 3.1415926-2.4-1.40.13 (TeX Live 2012)
 restricted \write18 enabled.
entering extended mode
This is pdfTeX, Version 3.1415926-2.4-1.40.13 (TeX Live 2012)
 restricted \write18 enabled.
entering extended mode


Error: Error running "pdflatex" to compile the LaTeX file.
Error: An error occured during creation of the report. Temporary files left in '/tmp/tmp3fSxZ4'.
Traceback (most recent call last):
  File "/usr/bin/sdaps", line 23, in <module>
    sys.exit(sdaps.main())
  File "/usr/lib64/python2.7/site-packages/sdaps/__init__.py", line 64, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib64/python2.7/site-packages/sdaps/script.py", line 105, in decorated_function
    result = function(cmdline)
  File "/usr/lib64/python2.7/site-packages/sdaps/cmdline/stamp.py", line 56, in stamp
    return stamp.stamp(survey, output, cmdline)
  File "/usr/lib64/python2.7/site-packages/sdaps/stamp/__init__.py", line 90, in stamp
    create_stamp_pdf(survey, output_filename, questionnaire_ids)
  File "/usr/lib64/python2.7/site-packages/sdaps/stamp/latex.py", line 48, in create_stamp_pdf
    raise AssertionError('PDF file not generated')
AssertionError: PDF file not generated
```

latex error log /tmp/tmp3fSxZ4/questionnaire.log can be found at http://pastebin.com/gdg1CST0

**Comment by benzea** [comment]
Hrm, that works without issues here (and on the ubuntu build server). And the log file is not very helpful unfortunately :-(

Maybe you could try if one of the IDs in data/tex/code128_test_ids causes the issue (most likely the last one).

**Comment by FloRinke** [comment]
Unfortunately your tip is only part of the truth. "[]()+-{}" is quite an ugly id, but simple "Hello" causes the same error. Interestingly, "12 Hello" is fine.

Also there is an additional error at projects/test-tex-no-ids, this also fails at stamping
The last lines of LaTeX output are
````
! Undefined control sequence.
\BODY ...kedbox {} crossed checkboxes, \filledbox
                                                  {} filled or \correctedbox...
l.145   \end{questionnaire}
````
(full log at http://pastebin.com/aabLtJnH)

I'm running texlive 2012, which is the latest stable on Gentoo. I'll have a look if I can upgrade this for reference testing.

**Comment by benzea** [comment]
Uhm, wait a minute. What version of SDAPS are you building? You are pulling in an old version of the sdaps.cls file from somewhere which is very likely causing all these issues.

**Comment by benzea** [comment]
I have not often bumped the internal file version of the SDAPS class. However it was updated in March 2013 which means that the class file used on your system predates the 1.0.0 release of SDAPS.

**Comment by FloRinke** [comment]
SDAPS 1.1.9 is installed on my system, and I'm running this from the 1.1.9 tarball.

And of course you're right, apparently there are old sdaps-latex files at /usr/share/texmf-site/tex/latex/sdaps/, while the current ones are at /usr/share/sdaps/tex/ (I wonder where they came from...)

LaTeX is currently in the middle of updating, so I'll test this later.

**Comment by benzea** [comment]
Ahhh!

I understand now. In the normal case the sdaps.cls file in the local directory is used. What happened now was that I am no longer copying the sdaps.cls file into the temporary directory for stamping. At the same time the search path is build in the wrong order, so that the project directory is last instead of second (after the temporary directory). Fix is being pushed.

**Comment by FloRinke** [comment]
Ah, that also explains why I didn't experience that failure with SDAPS 1.1.8. ^^
Deleting the old tex files has also fixed the problem with the current version.
Thanks for your help.
