### ISSUE TITLE
Latex macro inside markgroup

### ISSUE THREAD

**Issue by FloRinke** [sdaps/sdaps#65]
I used a Latex macro inside a markgroup/markline

``` latex
\newcommand{\trifftzu}{voll und ganz}
```

(Expression without space is easier for copy/paste ;-))

this works fine for the questionnaire, but fails horribly at the report as the generated tex file doesn't know my definitions (also the macro is not expanded in gui, but this doesn't really matter for me)

I'm not quite sure how easy it would be to evaluate the macros at setup, but is it possible to filter for expressions which will fail at later stages?

**Comment by benzea** [comment]
The best idea I have is to allow specifying a text that will be used in the GUI/the report. This is already planned for the next iteration of the LaTeX package/class.

**Comment by benzea** [comment]
Closing, as there will be no backport to the old class.

Note that it requires user intervention as you must ensure to set a replacement text for the report.
