### ISSUE TITLE
choiceitemtext minimum width is too large

### ISSUE THREAD

**Issue by fndercole** [sdaps/sdaps#68]
On a line 1187, in sdaps.cls
>    \setlength\@tempdima{2cm}

sets the minimum size for choiceitemtext box. 

2cm is too large for some cases. I propose 1cm or custom length, like
>    \minchoiceitemtextwidth

that can be change by users.

Best

fndercole

**Comment by benzea** [comment]
Huh, I seem to have totally overlooked this issue.

Yeah, we could just change it really. The user has to settle on a grid/table layout anyways ... how about setting the minimum to be the height of the box?
