### ISSUE TITLE
issue with Dutch translation error in translator-sdaps-dictionary-Dutch.dict

### ISSUE THREAD

**Issue by hstarmans** [sdaps/sdaps#70]
There is an issue with the Dutch translation of sdaps.  The translation results in the following text, tabaccklludge tabacckludge , which is giberish.
It can be resolved by modifying the dutch translation in , /usr/local/share/sdaps/tex
translator-sdaps-dictionary-Dutch.dict. The text has to be " mag slechts een hokje worden "
instead of "mag slechts {\@tabacckludge'e}{\@tabacckludge'e}n¨ .
Probably the aim of the dutch translation was to achieve "één" which emphasizes that you can only mark óné box. I have created a pull request with number #71 to fix this issue.

**Comment by benzea** [comment]
Btw. you can actually modify the translations directly on https://hosted.weblate.org/projects/sdaps/ and it will be committed to this repository automatically.

Though één should really just work. The trouble is that my code to translate the é into LaTeX macros uses a macro with the @ character which is not valid in the context. I'll need to look into why this is happening.
Which do you think is better in this context? "een" or "één" I really don't want to work around a bug in the translation generation script by modifying the translation itself :)

**Comment by benzea** [comment]
note to self: https://listserv.rediris.es/cgi-bin/wa?A2=ind0809&L=es-tex&F=&S=&P=43934 might be relevant ... need to do other things now though

**Comment by hstarmans** [comment]
"één"  looks better than "een".  Grammatically, however, een is correct. I will modify the translation on weblate.org so the problems is fixed as soon as possible and than will look into your macro.

**Comment by benzea** [comment]
Looks like I never get the hang on how to correctly mark the issues as fixed in the commit ... so now both versions will work just fine.
