### ISSUE TITLE
stamp command fails when using the \makenodeinlasttextbox hack

### ISSUE THREAD

**Issue by rongmu** [sdaps/sdaps#72]
Hi,

I was trying to collect subjects' age information via a freeform textbox.
I placed the text `____ Year __ Month __ Day` inside the textbox following the method suggested in SDAPS FAQ.

While the `setup_tex` proceeded without problem, the `stamp` command fails with pdflatex.
With xelatex, which is my real working environment because I create surveys in Chinese and Japanese,
it somehow works partially and only generates the pages for the very first id.

My environment: SDAPS 1.1.9 and Tex Live 2013 from the official Ubuntu 14.04 repo.

Here is the log file of pdflatex:
https://gist.github.com/rongmu/d5762f978a42876cbb9d

The latex source code I used for testing:
```tex
\documentclass[
  english,
  print_questionnaire_id,
  pagemark,
  stamp]{sdaps}

\usepackage[utf8]{inputenc}

\makeatletter
\newcommand{\makenodeinlasttextbox}[1]{%
  \begin{tikzpicture}[remember picture, overlay]%
    \setlength\textheight{\@sdaps@height}
    \advance\textheight by -2pt
    \node[outer sep=1pt, inner sep=0pt, align=center, text width=\@sdaps@width-2pt, minimum height=\textheight, shift={($(\@sdaps@x,\@sdaps@y) + 0.5*(\@sdaps@width, -\@sdaps@height)$)}, anchor=center] at (current page.south west) {%
      #1%
    };
  \end{tikzpicture}
}

\author{Test}
\title{Survey}

\begin{document}
  \begin{questionnaire}
    \section{Personal Information}
    \textbox*{2em}{Birthday}
    \makenodeinlasttextbox{%
      \underline{\phantom{YYYY}} Year
      \underline{\phantom{MM}} Month
      \underline{\phantom{DD}} Day
    }

    \begin{choicequestion}[2]{Gender}
      \choiceitem{Male}
      \choiceitem{Female}
    \end{choicequestion}

    % questions begin
    \section{Colorless green ideas sleep furiously.}
    \begin{choicequestion}[2]{Is this sentence grammatical?}
      \choiceitem{Yes}
      \choiceitem{No}
    \end{choicequestion}

  \end{questionnaire}
\end{document}
```

**Comment by benzea** [comment]
Oh, hmm. That makes sense. The hack relies on the position output code which is disabled after the first questionnaire (to conserve memory). So if you only stamp one at a time, then things will work fine.

You could also use

    {
    \makeatother
    \@sdaps@outputtrue
    \makeatletter
    \textbox*{2em}{Birthday}
    \makenodeinlasttextbox{%
      \underline{\phantom{YYYY}} Year
      \underline{\phantom{MM}} Month
      \underline{\phantom{DD}} Day
    }
    }

to enable output again just for that box. Note that the {} around everything are important as otherwise you will enable it again for all questions which uses a lot more memory.

**Comment by benzea** [comment]
Closing as I have added an explanation to http://sdaps.org/FAQ#Is_it_possible_to_put_content_inside_a_freeform_textbox.3F

**Comment by rongmu** [comment]
Thank you for your prompt reply.
I have tried the code ant it works well.

However I noticed that I have missed the `\makeatother` in the preamble in my test code.
After adding this back, it just adds a string "sdaps@outputtrue" before the question.

**Comment by benzea** [comment]
Whoops, yeah, makeatletter and makeatother were swapped in my example (funny that it even worked fine). I have fixed the above comment and the FAQ

**Comment by rongmu** [comment]
Thank you but unfortunately it doesn't seem to change much.
The string "sdaps@outputtrue" is still there and latex complains that `You can't use '\spacefactor' in vertical mode.`

**Comment by benzea** [comment]
Huh?Ohh, hrm, right. The \makeatletter and \makeatother commands must not be used inside the questionnaire environment (a rather ugly restriction of the environment that also breaks some other stuff).

Something like http://p.sipsolutions.net/5d174940b1d7b788.txt will work. I'll need to update the FAQ (please remind me in case I forget).

**Comment by rongmu** [comment]
Tried just now and it worked great.
You rock ;)

I guess it's better to update the FAQ sooner if possible to let other users know and benefit from this.

**Comment by benzea** [comment]
The FAQ has been updated a while ago (with a slightly different approach).
