### ISSUE TITLE
feature request; short cuts

### ISSUE THREAD

**Issue by hstarmans** [sdaps/sdaps#75]
At the moment, I am using SDAPS for a test we distribute on multiple schools.
I have to check up to 1200 pages per school. SDAPS works fine for this but I would like to optimize my work flow. I have three requests:
1. I would like to go to the following page via scrolling my mouse wheel if you are on the tiff field or a hotkey like the right arrow on the keyboard.
2. I really like the feature that you can click on the right answer in multiple choice questions.
What however does not really work well is text questions. You can click them so SDAPS knows something was answered. If you however want to write down the answer in the text field. You have to search for that field in the right pane, titled global properties.
What I would like is that if you double click a text based question, you immediately move to entering the text field in the Global properties plane. What would also work is that you get some sort of popup where you can enter the question. I want to do text based searches in my answers so that's why I prefer a typed answer.
3. If you go the next page the global properties sheet should also move to the next page.

PS.
1. The info of the project I use it for is available here ;  http://viruskenner.nl/?lang=en
2.
I can imagine SDAPS working well without the global properties tab. Looking at the coloured boxes in multiple choice questions, and with a popup for text based questions. You might not need the whole global properties field.
Typically sheets have a red border if your scroll over them. I would say they get a green border if they are "verified".
Moving to the first sheet which is not verified would also be nice, but not necessary.

**Comment by benzea** [comment]
It is easy to add more shortcuts. Do you already know the shortcuts
listed in http://sdaps.org/Documentation/GUI ?

On Sa, 2015-06-06 at 05:05 -0700, hstarmans wrote:
> At the moment, I am using SDAPS for a test we distribute on multiple
> schools.
> Per test, I have to check up to 1200 pages. SDAPS works fine for this
> but I would like to optimize my work process. I have two requests:
> 1. I would like to go to the following page via scrolling my mouse
> wheel or a hotkey like the right arrow on the keyboard.

Presssing Enter (or Tab) does this.

> 2. I really like the feature that you can click on the right answer in
> multiple choice questions.
> What however does not really work well is text questions. You can
> click them so SDAPS knows something was answered. If you however want
> to write down the answer in the text field. You have to search for
> that field in the right pane, titled global properties.

You don't. Right click on the field in the image. It will automatically
focus the text entry.

> What I would like is that if you double click a text based question,
> you immediately move to entering the text field in the Global
> properties plane. What also work is that you get some sort of popup
> where you can enter the question.
> 3. If you go the next page the global properties sheet should also
> move to the next page.

Hm, good point, we could automatically scroll so that the first element
of that page is at the top.

> PS.
> The info of the project I use it for is available here ;
> http://viruskenner.nl/?lang=en

Need to have a quick look later (GPRS connection right now)

**Comment by hstarmans** [comment]
Great +1:  guess most of the features I imagined are already there, thanks!

**Comment by benzea** [comment]
On Sa, 2015-06-06 at 05:31 -0700, hstarmans wrote:
> Great +1: guess most of the features I imagined are already there,
> thanks! 

Great! Would be nice if you play with it a bit and send some feedback
later. Maybe things can be improved some more :)

**Comment by benzea** [comment]
Closing, I think this is good enough. Though documentation is still lacking, I guess.
