### ISSUE TITLE
Trying setup...

### ISSUE THREAD

**Issue by steve-osfda** [sdaps/sdaps#77]
I am on CentOS 7; python version is 2.7.5

After adding some packages, I finally got sdaps to install without incident.
Then when I ran "sdaps test setup_tex example.tex" in my home directory, using the example.tex from the tutorial, I got:

# sdaps test setup_tex example.tex 
------------------------------------------------------------------------------
- SDAPS -- setup_tex
------------------------------------------------------------------------------
Running pdflatex now twice to generate the questionnaire.
Error: An error occured in the setup routine. The survey directory still exists. You can for example check the questionnaire.log file for LaTeX compile errors.
Traceback (most recent call last):
  File "/usr/bin/sdaps", line 23, in <module>
    sys.exit(sdaps.main())
  File "/usr/lib64/python2.7/site-packages/sdaps/__init__.py", line 64, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib64/python2.7/site-packages/sdaps/cmdline/setuptex.py", line 47, in setup_tex
    return setuptex.setup(survey, cmdline['questionnaire.tex'], cmdline['additional_questions'], cmdline['add'])
  File "/usr/lib64/python2.7/site-packages/sdaps/setuptex/__init__.py", line 116, in setup
    latex.compile('questionnaire.tex', cwd=survey.path())
  File "/usr/lib64/python2.7/site-packages/sdaps/utils/latex.py", line 122, in compile
    run_engine(texfile, cwd, inputs)
  File "/usr/lib64/python2.7/site-packages/sdaps/utils/latex.py", line 118, in run_engine
    preexec_fn=_preexec_fn)
  File "/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Ideas?

**Comment by benzea** [comment]
SDAPS requires some more external utitlies (not all of them are needed for every mode of operation).

In this case you are missing an installation of texlive (i.e. the pdflatex command).

**Comment by steve-osfda** [comment]
Yes, I just figured that out (surprised the install didn't complain about that being missing...)

Now I am getting a little further along, but I hit a failure in questionnaire.log, about "xargs.sty' not found":

Babel <v3.8m> and hyphenation patterns for english, dumylang, nohyphenation, loaded.
(./sdaps.cls
Document Class: sdaps 2013/03/10v1.0 Class for composing questionairs for SDAPS

(/usr/share/texlive/texmf-dist/tex/latex/koma-script/scrkbase.sty
Package: scrkbase 2012/07/29 v3.11b KOMA-Script package (KOMA-Script-dependent basics and keyval usage)
(/usr/share/texlive/texmf-dist/tex/latex/koma-script/scrbase.sty
Package: scrbase 2012/07/29 v3.11b KOMA-Script package (KOMA-Script-independent
 basics and keyval usage)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 1999/03/16 v1.13 key=value parser (DPC)
\KV@toks@=\toks14
) (/usr/share/texlive/texmf-dist/tex/latex/koma-script/scrlfile.sty
Package: scrlfile 2012/06/15 v3.12 KOMA-Script package (loading files)
Package scrlfile, 2012/06/15 v3.12 KOMA-Script package (loading files)
                  Copyright (C) Markus Kohm)))

! LaTeX Error: File `xargs.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

**Comment by steve-osfda** [comment]
The problem now evidently is I need the "xargs" Latex package (another one I'm surprised the install did not assert...) xargs is not standard in the CentOS texlive package, so I am trying to figure out how to add it. Supposedly it is easy with a Latex installer command called "tlmgr", but that is also not part of CentOS texlive...

**Comment by benzea** [comment]
Ah, the install just checks for the bare minimum required to compile and install SDAPS itself. The thing is that the tex support is a soft dependency, in the sense that you don't need that stuff you just use the ODT/LibreOffice support.

**Comment by steve-osfda** [comment]
Another problem knocked out: CentOS repositories had a texlive package; but sdaps needs the one from:
https://www.tug.org/texlive/acquire-netinstall.html

Considering how many people use CentOS, that one's going to bite a lot of people!

Thanks for your help thus far...
