### ISSUE TITLE
Error after shutdown

### ISSUE THREAD

**Issue by fndercole** [sdaps/sdaps#79]
Hi, 
After editing data in a GUI session, I closed and save changes, but involuntarily I forced GUI to close before the job was done. 

After that, I get a error message when I tried to reopen a GUI or export to csv. 
```
Traceback (most recent call last):
  File "/usr/bin/sdaps", line 23, in <module>
    sys.exit(sdaps.main())
  File "/usr/lib/python2.7/dist-packages/sdaps/__init__.py", line 64, in main
    return cmdline['_func'](cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/script.py", line 105, in decorated_function
    result = function(cmdline)
  File "/usr/lib/python2.7/dist-packages/sdaps/cmdline/gui.py", line 41, in gui
    survey = model.survey.Survey.load(cmdline['project'])
  File "/usr/lib/python2.7/dist-packages/sdaps/model/survey.py", line 149, in load
    survey = cPickle.load(file)
EOFError
```

Now, I can't find the way to recover the database.
Thanks, for your help.
Best

**Comment by benzea** [comment]
:-(

This is bad, and the data is gone, I fear. I had not reallized that before, but the save function does not guard against errors, so effectively destroys the file should it be interrupted. This is a pretty bad bug, and actually rather easy to fix.

In this case, you probably need to recreate the project, and re-run the recognition process after adding the images back. Unfortunately, that means that any manual correction needs to be redone :-/

**Comment by fndercole** [comment]
Maybe if I recover disk deleted data, i can found an old version of the file.
¿What type of file is "survey"? Nautilus identify like a archiver, but I think that is other type.

**Comment by benzea** [comment]
It is a bzip compressed python pickle file.

**Comment by fndercole** [comment]
I found several bzip files with photorec. I will try to discover which is the right.
If this this fails, I will try to import csv with 90% of manual corrections (is a lot of works). 
Thanks!!

**Comment by fndercole** [comment]
Finally, I decided to recreate the project and import the previous csv files.

But, the import command doesn't work. After a revision of the code, I changed the following lines from sdaps/sdaps/csvdata/buddies.py:

line 66, I have questionnarie_id with characters, so it can't be converted to int. 

```python
    def import_data(self, data):
        try:
            self.obj.survey.goto_questionnaire_id(data['questionnaire_id']) 
            # self.obj.survey.goto_questionnaire_id(int(data['questionnaire_id']))
        except ValueError:
            # The sheet does not exist
            # Ignore it
            pass
        else:
            for qobject in self.obj.qobjects:
                qobject.csvdata.import_data(data)
```

After that, data was imported but I get this error when I try to export again:
```
File "/usr/lib/python2.7/dist-packages/sdaps/csvdata/buddies.py", line 241, in export_data
    data = self.obj.data.text.encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'
```

line 257, I use ```text``` instead ```state``` to fix this error 
```python
    def import_data(self, data):
        try:
            state = int(data)
            text = u''
        except ValueError:
            state = 1
            text = unicode(data)

        self.obj.data.state = state
        self.obj.data.text = text
        # self.obj.data.text = state
```

Now, import works for me. My apologies if I have misinterpreted the code.

Best

**Comment by benzea** [comment]
Oh, your interpretation of the code was entirely correct. Only weird thing that you could not know is, that questionnaire ids may be either a string or number depending on the "style".
