### ISSUE TITLE
Extension for "range" questions

### ISSUE THREAD

**Issue by ysalmon** [sdaps/sdaps#80]
This is to announce that I wrote a small extension for the classical sdaps LaTeX class. It allows for range questions, ie. answer matrix that are displayed as choicegroups in the PDF but treated as markgroup in the CSV export : you will get the checked numerical value instead of columns of zeroes and ones. I find it useful for asking for e.g. date of birth.
The sty file is available from [my sdaps fork](https://github.com/ysalmon/sdaps/tree/sdaps-range) and contains more details and some usage examples.
![questionnaire](https://cloud.githubusercontent.com/assets/536850/9428272/7e205372-49a7-11e5-9a24-231fe85dff0a.png)

**Comment by benzea** [comment]
Neat, may be nice to merge, or I may at least try to implement it in the new class.

**Comment by egga72** [comment]
Hi,
Would it be possible to share the sty file again as the link is not working anymore?
Would be very helpful for my work.
Thanks!

**Comment by ysalmon** [comment]
I deleted the old PR to sdaps-class as this repo only deals with the new (or rather future) class.
I edited my initial post to point to a fork of the stable branch of the main sdaps repo, where the old class and its extensions reside.

**Comment by benzea** [comment]
@egga72, please note that the code will currently *not* work with the unstable 1.9.x release as it does not include the old "sdaps.cls" class.

**Comment by egga72** [comment]
Thx for the information. Have already noticed this. Would be a great feature.

**Comment by benzea** [comment]
In the new class you can switch the mode to "singlechoice" instead of "multichoice" now for a similar effect.

What is still missing compared to your code though:

1. grid lines
2. the trick for the date where day/month have a different amount of columns

**Comment by benzea** [comment]
Do you think the current solution is sufficient? What are the biggest pain points for you?

It might be worth opening a new issue for that so as to keep things more organised.

**Comment by benzea** [comment]
Closing this one. Please open new issues for anything that you find important.

I know that the solution is not perfect, but would like to understand the requirements better before working on solutions.
