### ISSUE TITLE
duplex scanning, twoside...

### ISSUE THREAD

**Issue by steve-osfda** [sdaps/sdaps#81]
I want to make a two-sided questionnaire; I can then use the "twoside" latex directive, and make sure the stamped pdf pages get printed on the front and back of each paper page.

The issue is: my scanner does not generate mtiffs; it makes one tiff for each side of the page scanned (when scanning duplex, as opposed to making a single mtiff...); the tiffs are named in order, so I know which is the front and back of each page.

So just checking: if I take two successive tiffs and combine them with an ImageMagick convert (example: convert side1.tiff side2.tiff scan.tiff), then when I add them I use:

sdaps {project_dir} add --duplex scan.tiff

?

**Comment by benzea** [comment]
sure, as http://sdaps.org/Documentation/Scanning also says. You may want to use tiffcp though, as that is much faster.

**Comment by steve-osfda** [comment]
I saw that utility; thanks for the tip on its speed!
