### ISSUE TITLE
Inspection of Page Number and Orientation...

### ISSUE THREAD

**Issue by steve-osfda** [sdaps/sdaps#82]
I see that in recognize/qrcode.py (I happen to be scanning that style...) there are the functions get_page_rotation and get_page_number. I understand that sdaps does not re-orient images since its focus is to just record selected results -but I need to.

I figured out that one option is for me to modify these functions so that the page numbers and orientations of the sequential scans are logged to a file during the recognize process.

I looked at the possibility of calling those functions directly in a separate pass, but it appeared to require a lot of setup that would be slow. Is there an example anywhere where I can succinctly load an image and invoke just those functions? I'm not interested in knowing much else if I do this separate pass approach.

**Comment by benzea** [comment]
Please have a look at https://github.com/sdaps/sdaps/blob/master/custom-scripts/sdaps-identify.py which basically does what you need, I expect. You might also want to look at the overlay script; it has code to load the images and generate a PDF.

**Comment by steve-osfda** [comment]
That does look like the ticket; thanks
(give me a little time to play with it before I close this...)

**Comment by benzea** [comment]
Closing anyways …

As I already said, this is not a support forum; please direct your question to the mailinglist instead.

**Comment by steve-osfda** [comment]
OK; I'll try and get that working for me...
