### ISSUE TITLE
use "makedirs" instead of "mkdir"

### ISSUE THREAD

**Issue by marvin2k** [sdaps/sdaps#85]
Hi,

creating a survey with `setup_tex` inside a multi-level subfolder fails currently. This patch remedies the problem:

```patch
diff --git a/sdaps/setupodt/__init__.py b/sdaps/setupodt/__init__.py
index 75e0dbb..7156a25 100644
--- a/sdaps/setupodt/__init__.py
+++ b/sdaps/setupodt/__init__.py
@@ -132,7 +132,7 @@ def setup(survey, questionnaire_odt, questionnaire_pdf, additionalqobjects, opti
     print unicode(survey.questionnaire)
 
     # Create the survey
-    os.mkdir(survey.path())
+    os.makedirs(survey.path())
 
     log.logfile.open(survey.path('log'))
 
diff --git a/sdaps/setuptex/__init__.py b/sdaps/setuptex/__init__.py
index 79a0133..f9ceab4 100644
--- a/sdaps/setuptex/__init__.py
+++ b/sdaps/setuptex/__init__.py
@@ -83,7 +83,7 @@ def setup(survey, questionnaire_tex, additionalqobjects=None, extra_files=[]):
     survey.add_questionnaire(model.questionnaire.Questionnaire())
 
     # Create the survey directory, and copy the tex file.
-    os.mkdir(survey.path())
+    os.makedirs(survey.path())
     try:
         shutil.copy(questionnaire_tex, survey.path('questionnaire.tex'))
 
```

works for me... ;-)

**Comment by benzea** [comment]
Sounds good. Could you either create a patch using "git format-patch", send it by e-mail (git send-email), or create a pull request here? That way the commit will be correctly attributed to you and you can include a commit message.

**Comment by marvin2k** [comment]
meh ;-) Here you go, hope that ok.

On 11/27/2015 03:45 PM, Benjamin Berg wrote:
>
> Sounds good. Could you either create a patch using "git format-patch", 
> send it by e-mail (git send-email), or create a pull request here? 
> That way the commit will be correctly attributed to you and you can 
> include a commit message.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sdaps/sdaps/issues/85#issuecomment-160153064>.
>

-- 
M.Sc. Martin Zenzes
Space Robotics

Hauptgeschäftsstelle Standort Bremen:
DFKI GmbH
Robotics Innovation Center
Robert-Hooke-Straße 5
28359 Bremen, Germany

Phone: +49 (0) 421 178 45 - 6658
Fax: +49 (0) 421 178 45 - 4150
E-Mail: martin.zenzes@dfki.de

Weitere Informationen: http://www.dfki.de/robotik
-----------------------------------------------------------------------
Deutsches Forschungszentrum fuer Kuenstliche Intelligenz GmbH
Firmensitz: Trippstadter Straße 122, D-67663 Kaiserslautern
Geschaeftsfuehrung: Prof. Dr. Dr. h.c. mult. Wolfgang Wahlster
(Vorsitzender) Dr. Walter Olthoff
Vorsitzender des Aufsichtsrats: Prof. Dr. h.c. Hans A. Aukes
Amtsgericht Kaiserslautern, HRB 2313
Sitz der Gesellschaft: Kaiserslautern (HRB 2313)
USt-Id.Nr.: DE 148646973
Steuernummer: 19/673/0060/3
-----------------------------------------------------------------------
