### ISSUE TITLE
black right-side panel in the gui

### ISSUE THREAD

**Issue by bzimage-it** [sdaps/sdaps#89]
Gui looks completely black on the right side. see screenshot.

version is: sdaps-1.1.11

some system info:

`$ uname -a`
`Linux casa 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:02 UTC 2015 i686 i686 i686 GNU/Linux`

`$ apt --installed list > ~/apt_installed_list.txt`
`$ lsb_release -a > ~/lsb_release_a.txt`

in the attached files

[apt_installed_list.txt](https://github.com/sdaps/sdaps/files/102588/apt_installed_list.txt)
![screenshot from 2016-01-24 23 32 14](https://cloud.githubusercontent.com/assets/16113430/12539441/c360574c-c2f2-11e5-8b5c-742996d6c629.png)
[lsb_release_a.txt](https://github.com/sdaps/sdaps/files/102589/lsb_release_a.txt)

**Comment by benzea** [comment]
Uh, that is rather weird. That is a normal GtkViewPort with a GtkBox stacked inside.

This may actually be a theme bug where the background is not properly painted for the scrolled window (which you wouldn't notice most of the time, as many widgets would paint over the black area).

Or there is an issue with the clipping while drawing the left hand side.

**Comment by benzea** [comment]
I have confirmed with the GTK+ developers that this is likely an issue with the Ubuntu specific theme. You can try switchting to another GTK+ theme (e.g. Adwaita) or maybe upgrade the system to get a fixed version.

It is a bit unfortunate, but working around it in SDAPS itself would likely be quite complicated. If you find a workaround, it would be nice if you add a short description here.
