### ISSUE TITLE
Modify the shbang to specify python2

### ISSUE THREAD

**Issue by ytterbium** [sdaps/sdaps#91]
When the default python executable is python3 (in ArchLinux for example), running sdaps.py doesn't work, since it calls `/usr/bin/env python` which is linked to python3.
The same problem exists in setup.py

The simple solution is to specify `#!/usr/bin/env python2` as the shebang in sdaps.py and setup.py

**Comment by benzea** [comment]
Well, I don't really agree with what arch has done there. And IIRC back
when we started not all distribution had a python2 alias at the point.
(see also https://www.python.org/dev/peps/pep-0394/)

Anyways, shouldn't be an issue to specify python2 these days, so we can
make the change now.
