### ISSUE TITLE
SDAPS GUI markers not aligning with content

### ISSUE THREAD

**Issue by roshbosh** [sdaps/sdaps#95]
I have an issue with the GUI, where the (blue) markers are not aligning with the content ( check-boxes and text fields) Please see below image -

![image](https://cloud.githubusercontent.com/assets/8665376/21964832/b9a57098-db79-11e6-97b4-afd9de1695d5.png)

These boxes gets aligned, only when I zoom the pdf by a lot (Maximum zoom)

Also is there a method to stop the formatting tags which are added in the latex file ( in this case to make the subject bold) appearing in the report - 
![image](https://cloud.githubusercontent.com/assets/8665376/21964902/b95f1ebc-db7a-11e6-8e79-612e25541921.png)

Would be grateful if anyone can suggest a solution for these issues.

Thanks in advance.

**Comment by benzea** [comment]
On Sun, 2017-01-15 at 10:03 -0800, roshbosh wrote:
> These boxes gets aligned, only when I zoom the pdf by a lot (Maximum
> zoom)

What version of SDAPS and GTK+ are you using? Some older versions have
rendering errors with new GTK+ versions. Though zoom changing things is
a bit weird.

> Would be grateful if anyone can suggest a solution for these issues.

Try the LaTeX based report. There isn't a real solution for this right
now (there is only half finished development work).

**Comment by benzea** [comment]
Alright, I'll assume that the first issue is fixed by an update to SDAPS (i.e. that the bug is for a really old version).

The second issue is properly fixed in the unstable branch at this point, as you can specify a replacement text for the report with the new LaTeX class.
