### ISSUE TITLE
sdaps is working in Windows 10 using Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by scottlawsonbc** [sdaps/sdaps#96]
Hello,

I just want to report that I was able to run sdaps on Windows 10 using the new Windows Subsystem for Linux (WSL). Installing sdaps on Bash on Ubuntu on Windows was straightforward and I experienced no issues running sdaps. Even the GUI works!

You may want to consider adding a note about this in the documentation. Feel free to use any of text I've summarized below.

#### Windows Subsystem for Linux

In case you are not aware, a recent update to Windows 10 introduced [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about) and the [Windows Subsystem for Linux](https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/). This is *not* the same thing as a virtual machine, Bash on Ubuntu on Windows enables native Linux ELF64 binaries to run on Windows via the Windows Subsystem for Linux.

#### sdaps on Windows 10

Windows 10 users can install sdaps using Bash on Ubuntu on Windows, a feature that was added in the Windows 10 anniversary update. [To install Bash on Ubuntu on Windows, see this installation guide](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide).

Installing sdaps using Bash on Ubuntu on Windows is identical to any typical Ubuntu install:
```
add-apt-repository ppa:benjamin-sipsolutions/sdaps
apt-get update
apt-get install sdaps
```

The sdaps GUI can be used on Windows 10 through an X server such as Xming. After starting a Windows X server, type the following into Bash on Ubuntu on Windows. Once this is done the GUI should load in Windows the next time the sdaps GUI is run.

```
export DISPLAY=:0.
```

![image](https://cloud.githubusercontent.com/assets/2927085/22394806/43209e2e-e4df-11e6-9d30-3a648d98fefd.png)

**Comment by benzea** [comment]
Oh, interesting. Kind of makes sense that this is possible, still surprises me that it seems relatively straight forward to get everything running.

I'll want to dedicate some spare cycles to update the website some time after mid February. Feel free to ping me again at that time so that the website is updated!

**Comment by benzea** [comment]
Thanks, I finally got around to updating the website. I did use your screenshot, I hope that is fine with you.

Feel free to suggest any further improvements. See http://sdaps.org/Download/#windows

**Comment by rongmu** [comment]
The right panel of the GUI was missing in my environment of Bash on Ubuntu on Windows.
I solved the problem by disabling the "overlay scrollbars":

`export GTK_OVERLAY_SCROLLING=0`

This might help people with similar issues.

**Comment by benzea** [comment]
Alright, i added it into the instruction and added a note. Would be good to know what is going wrong, but luckily the workaround is easy.

**Comment by Londane** [comment]
@benzea  It seems that the website changed. 
The link does not work + there is not hint about windows on the install page.
Is this approach is still relevant ?

**Comment by benzea** [comment]
We changed the website since then.

Windows is problematic. What you can do is to use WSL2, but really, that is just an almost standard Linux installation on top of windows, so one should be able to follow the Linux instructions without much of a change.

**Comment by Londane** [comment]
Thank very much! 
You i will give it a try.
